/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices
 */

@interface ASWebAuthenticationSession : NSObject {
    SFAuthenticationSession * _authenticationSession;
    id /* block */  _originalCompletionHandler;
    bool  _prefersEphemeralWebBrowserSession;
    <ASWebAuthenticationPresentationContextProviding> * _presentationContextProvider;
    ASWebAuthenticationSession * _referenceToSelf;
}

@property (nonatomic) bool prefersEphemeralWebBrowserSession;
@property (nonatomic) <ASWebAuthenticationPresentationContextProviding> *presentationContextProvider;

- (void).cxx_destruct;
- (void)_invalidate;
- (void)cancel;
- (id)initWithURL:(id)arg1 callbackURLScheme:(id)arg2 completionHandler:(id /* block */)arg3;
- (id)initWithURL:(id)arg1 callbackURLScheme:(id)arg2 usingEphemeralSession:(bool)arg3 completionHandler:(id /* block */)arg4;
- (bool)prefersEphemeralWebBrowserSession;
- (id)presentationContextProvider;
- (void)setPrefersEphemeralWebBrowserSession:(bool)arg1;
- (void)setPresentationContextProvider:(id)arg1;
- (bool)start;

@end
