/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHAvailabilityRequest : NSObject {
    NSManagedObjectID * _assetObjectID;
    NSXPCConnection * _clientConnection;
    _Atomic bool  _isCancelled;
    PLPhotoLibrary * _photoLibrary;
    unsigned long long  _signpostID;
    NSString * _taskIdentifier;
}

@property (nonatomic, readonly) NSManagedObjectID *assetObjectID;
@property (nonatomic, retain) NSXPCConnection *clientConnection;
@property (nonatomic, readonly) PLPhotoLibrary *photoLibrary;
@property (nonatomic) unsigned long long signpostID;
@property (nonatomic, readonly, copy) NSString *taskIdentifier;

- (void).cxx_destruct;
- (void)abortClientSide;
- (id)assetObjectID;
- (void)cancel;
- (id)clientConnection;
- (id)description;
- (id)initWithPlistDictionary:(id)arg1 photoLibrary:(id)arg2;
- (id)initWithTaskIdentifier:(id)arg1 assetObjectID:(id)arg2;
- (bool)isCancelled;
- (id)photoLibrary;
- (id)plistDictionary;
- (void)runDaemonSide;
- (void)setClientConnection:(id)arg1;
- (void)setSignpostID:(unsigned long long)arg1;
- (unsigned long long)signpostID;
- (id)taskIdentifier;

@end
