/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Photos.framework/Photos
 */

@interface PHPhotoLibraryAppPrivateData : NSObject {
    PLAppPrivateData * _impl;
}

@property (retain) PLAppPrivateData *impl;

+ (bool)accessInstanceVariablesDirectly;

- (void).cxx_destruct;
- (id)debugDescription;
- (id)dictionaryWithValuesForKeys:(id)arg1;
- (id)impl;
- (id)initWithLibrary:(id)arg1;
- (void)invalidate;
- (void)setImpl:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (void)setValue:(id)arg1 forKeyPath:(id)arg2;
- (void)setValuesForKeysWithDictionary:(id)arg1;
- (id)valueForKey:(id)arg1;
- (id)valueForKeyPath:(id)arg1;

@end
