/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSAssetUploadObserver : NSObject {
    CLSAsset * _asset;
    id /* block */  _onUploadComplete;
    id /* block */  _onUploadProgress;
    id /* block */  _preCompleteHook;
    NSMetadataQuery * _query;
    NSError * _uploadError;
    NSOperationQueue * _uploadObserverQueue;
    double  _uploadProgress;
}

@property (nonatomic, retain) CLSAsset *asset;
@property (nonatomic, copy) id /* block */ onUploadComplete;
@property (nonatomic, copy) id /* block */ onUploadProgress;
@property (nonatomic, copy) id /* block */ preCompleteHook;
@property (nonatomic, retain) NSMetadataQuery *query;
@property (retain) NSError *uploadError;
@property (nonatomic, retain) NSOperationQueue *uploadObserverQueue;
@property double uploadProgress;
@property (getter=isUploaded, nonatomic) bool uploaded;

- (void).cxx_destruct;
- (void)_notifyOfChange;
- (void)_notifyOfCompletion;
- (void)_processItems:(id)arg1;
- (id)asset;
- (id)init;
- (id)initWithAsset:(id)arg1;
- (bool)isUploaded;
- (id /* block */)onUploadComplete;
- (id /* block */)onUploadProgress;
- (id /* block */)preCompleteHook;
- (id)query;
- (void)queryGatheredData:(id)arg1;
- (void)queryUpdated:(id)arg1;
- (void)setAsset:(id)arg1;
- (void)setOnUploadComplete:(id /* block */)arg1;
- (void)setOnUploadProgress:(id /* block */)arg1;
- (void)setPreCompleteHook:(id /* block */)arg1;
- (void)setQuery:(id)arg1;
- (void)setUploadError:(id)arg1;
- (void)setUploadObserverQueue:(id)arg1;
- (void)setUploadProgress:(double)arg1;
- (void)setUploaded:(bool)arg1;
- (void)startObserving;
- (void)stopObserving;
- (id)uploadError;
- (id)uploadObserverQueue;
- (double)uploadProgress;

@end
