/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ClassKit.framework/ClassKit
 */

@interface CLSCurrentUser : NSObject <NSCopying, NSSecureCoding> {
    int  _devMode;
    NSDictionary * _locationIDsByAXMRoleType;
    CLSPerson * _person;
    unsigned long long  _roles;
}

@property (nonatomic) int devMode;
@property (nonatomic, readonly) bool isAdministrator;
@property (nonatomic, readonly) bool isInstructor;
@property (nonatomic, readonly) bool isStudent;
@property (nonatomic, retain) NSDictionary *locationIDsByAXMRoleType;
@property (nonatomic, retain) CLSPerson *person;
@property (nonatomic) unsigned long long roles;

+ (id)magicValue;
+ (bool)supportsSecureCoding;
+ (unsigned long long)userRolesFromUserLocationIDsByAXMRoleType:(id)arg1;

- (void).cxx_destruct;
- (bool)_hasRole:(unsigned long long)arg1;
- (id)_init;
- (unsigned long long)_useRoles;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (int)devMode;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasRole:(unsigned long long)arg1;
- (id)initWithCoder:(id)arg1;
- (bool)isAdministrator;
- (bool)isInstructor;
- (bool)isStudent;
- (id)locationIDsByAXMRoleType;
- (id)person;
- (unsigned long long)roles;
- (void)setDevMode:(int)arg1;
- (void)setLocationIDsByAXMRoleType:(id)arg1;
- (void)setPerson:(id)arg1;
- (void)setRoles:(unsigned long long)arg1;

@end
