/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtCV7SwiftUI11DisplayList11ViewUpdater : Swift._SwiftObject {
    void contentsScale;
    void isValid;
    void seed;
    void viewCache;
    void wasValid;
}

@end
