/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtC7SwiftUIP33_023AA827B8A8D39774F7A0C281455FEE24DynamicAnimationListener : Swift._SwiftObject {
    void asyncSignal;
    void count;
    void viewGraph;
}

@end
