/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtC7SwiftUIP33_DAAACAB0B71F0997824BE4289855D4428StateBox : Swift._SwiftObject {
    void activeCount;
    void animation;
    void fraction;
    void isActive;
    void phase;
    void reversed;
    void sampler;
    void sentCompletion;
    void startFraction;
}

@end
