/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtCV7SwiftUIP33_7647B8DD4181297A53FB830E389DD7E015UIKitDatePicker11Coordinator : SwiftUI.PlatformViewCoordinator {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  configuration;
}

- (void).cxx_destruct;
- (void)dateChanged:(id)arg1;
- (id)init;

@end
