/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtC7SwiftUIP33_FD2B36BBCDC44C2A4C267987C06FEA7111Coordinator : SwiftUI.PlatformViewCoordinator {
    void configuration;
}

- (void).cxx_destruct;
- (void)editingBegan:(id)arg1;
- (void)editingEnded:(id)arg1;
- (id)init;
- (void)valueChanged:(id)arg1;

@end
