/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtCV7SwiftUI16DynamicContainer8ItemInfo : Swift._SwiftObject {
    void listener;
    void needsTransitions;
    void outputs;
    void phase;
    void precedingViewCount;
    void removalOrder;
    void resetSeed;
    void subgraph;
    void uniqueId;
    void viewCount;
    void zIndex;
}

@end
