/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtC7SwiftUIP33_D63C4EB7F2B205694B6515509E76E98B16AsyncTransaction : Swift._SwiftObject {
    void mutations;
    void transaction;
}

@end
