/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtC7SwiftUIP33_3B7895BFA1A67E95213A2DB77120A33F12ListenerNode : Swift._SwiftObject {
    void listener;
    void next;
}

@end
