/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtCV7SwiftUI4Path7PathBox : Swift._SwiftObject {
    void bounds;
    void cgPath;
}

@end
