/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtCV7SwiftUI12_ViewList_ID5Views : Swift._SwiftObject {
    void isDataDependent;
}

@end
