/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface _TtCV7SwiftUI12PropertyList7Element : Swift._SwiftObject {
    void after;
    void before;
    void keyFilter;
    void keyType;
    void length;
}

@end
