/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI._ViewList_Subgraph : Swift._SwiftObject {
    void refcount;
    void subgraph;
}

@end
