/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.RBGraphicsContext : Swift._SwiftObject {
    void _blendMode;
    void clipLayer;
    void fill;
    void linearColors;
    void list;
    void opacity;
    void savedState;
    void shape;
}

@end
