/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.EventBindingManager : Swift._SwiftObject {
    void delegate;
    void eventBindingSeed;
    void eventBindings;
    void eventTimer;
    void host;
    void isActive;
}

@end
