/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.DisplayLink : Swift._SwiftObject {
    void host;
    void link;
}

- (void)displayLinkTimer:(id)arg1;

@end
