/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.PreferenceBridge : Swift._SwiftObject {
    void bridgedPreferences;
    void bridgedViewInputs;
    void invalidationCallback;
    void preferencesNeedUpdate;
    void requestedPreferences;
    void viewGraph;
}

@end
