/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.ResolvedStyledText : Swift._SwiftObject {
    void $__lazy_storage_$_oversizeCharacterOutsets;
    void cache;
    void lineLimit;
    void lineSpacing;
    void minScaleFactor;
    void pixelLength;
    void scaleFactorOverride;
    void string;
    void truncationMode;
}

@end
