/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.ViewResponder : Swift._SwiftObject {
    void parent;
    void viewRendererHost;
}

@end
