/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.EmptyViewRendererHost : Swift._SwiftObject {
    void currentTimestamp;
    void eventBindingManager;
    void isRendering;
    void needsEnvironmentUpdate;
    void needsRootViewUpdate;
    void viewGraph;
}

@end
