/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.ScrollTest : Swift._SwiftObject {
    void parameters;
    void testRunner;
}

@end
