/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
 */

@interface SwiftUI.UIViewResponder : SwiftUI.ViewResponder {
    void focusAccessibilityNode;
    void hostView;
    void representedView;
}

@end
