/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface MFComposeSendAccessoryButton : UIButton {
    UIImage * _sendImage;
}

@property (nonatomic, retain) UIImage *sendImage;

+ (id)buttonWithType:(long long)arg1;

- (void).cxx_destruct;
- (void)_setupSendImage:(bool)arg1;
- (id)sendImage;
- (void)setEnabled:(bool)arg1;
- (void)setSendImage:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end
