/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface MFMailComposeRecipientTextView : CNComposeRecipientTextView {
    MFComposeDisplayMetrics * _displayMetrics;
}

@property (nonatomic) <MFMailComposeRecipientTextViewDelegate> *delegate;
@property (nonatomic, retain) MFComposeDisplayMetrics *displayMetrics;

- (void).cxx_destruct;
- (void)_displayMetricsDidChange;
- (void)_textInputDidChange:(id)arg1;
- (void)dealloc;
- (id)displayMetrics;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutMarginsDidChange;
- (id)nextResponder;
- (void)setDisplayMetrics:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;

@end
