/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface MFMediaExporter : NSObject

+ (id)conversionTimers;
+ (int)exportAsset:(id)arg1 progressHandler:(id /* block */)arg2 completion:(id /* block */)arg3;
+ (void)setConversionTimers:(id)arg1;

@end
