/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface _WKWebsiteDataStoreConfiguration : NSObject <WKObject> {
    struct ObjectStorage<WebKit::WebsiteDataStoreConfiguration> { 
        struct type { 
            unsigned char __lx[256]; 
        } data; 
    }  _configuration;
}

@property (readonly) struct Object { int (**x1)(); id x2; }*_apiObject;
@property (setter=_setCacheStorageDirectory:, nonatomic, copy) NSURL *_cacheStorageDirectory;
@property (setter=_setCookieStorageFile:, nonatomic, copy) NSURL *_cookieStorageFile;
@property (setter=_setIndexedDBDatabaseDirectory:, nonatomic, copy) NSURL *_indexedDBDatabaseDirectory;
@property (setter=_setResourceLoadStatisticsDirectory:, nonatomic, copy) NSURL *_resourceLoadStatisticsDirectory;
@property (setter=_setServiceWorkerRegistrationDirectory:, nonatomic, copy) NSURL *_serviceWorkerRegistrationDirectory;
@property (setter=_setWebSQLDatabaseDirectory:, nonatomic, copy) NSURL *_webSQLDatabaseDirectory;
@property (setter=_setWebStorageDirectory:, nonatomic, copy) NSURL *_webStorageDirectory;
@property (nonatomic) bool allLoadsBlockedByDeviceManagementRestrictionsForTesting;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool deviceManagementRestrictionsEnabled;
@property (readonly) unsigned long long hash;
@property (setter=setHTTPProxy:, nonatomic, copy) NSURL *httpProxy;
@property (setter=setHTTPSProxy:, nonatomic, copy) NSURL *httpsProxy;
@property (getter=isPersistent, nonatomic, readonly) bool persistent;
@property (nonatomic, copy) NSString *sourceApplicationBundleIdentifier;
@property (nonatomic, copy) NSString *sourceApplicationSecondaryIdentifier;
@property (readonly) Class superclass;

- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (id)_cacheStorageDirectory;
- (id)_cookieStorageFile;
- (id)_indexedDBDatabaseDirectory;
- (id)_resourceLoadStatisticsDirectory;
- (id)_serviceWorkerRegistrationDirectory;
- (void)_setCacheStorageDirectory:(id)arg1;
- (void)_setCookieStorageFile:(id)arg1;
- (void)_setIndexedDBDatabaseDirectory:(id)arg1;
- (void)_setResourceLoadStatisticsDirectory:(id)arg1;
- (void)_setServiceWorkerRegistrationDirectory:(id)arg1;
- (void)_setWebSQLDatabaseDirectory:(id)arg1;
- (void)_setWebStorageDirectory:(id)arg1;
- (id)_webSQLDatabaseDirectory;
- (id)_webStorageDirectory;
- (bool)allLoadsBlockedByDeviceManagementRestrictionsForTesting;
- (bool)deviceManagementRestrictionsEnabled;
- (id)httpProxy;
- (id)httpsProxy;
- (id)init;
- (id)initNonPersistentConfiguration;
- (bool)isPersistent;
- (void)setAllLoadsBlockedByDeviceManagementRestrictionsForTesting:(bool)arg1;
- (void)setDeviceManagementRestrictionsEnabled:(bool)arg1;
- (void)setHTTPProxy:(id)arg1;
- (void)setHTTPSProxy:(id)arg1;
- (void)setSourceApplicationBundleIdentifier:(id)arg1;
- (void)setSourceApplicationSecondaryIdentifier:(id)arg1;
- (id)sourceApplicationBundleIdentifier;
- (id)sourceApplicationSecondaryIdentifier;

@end
