/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKBrowsingContextHandle : NSObject <NSSecureCoding> {
    struct ObjectIdentifier<WebCore::PageIdentifierType> { 
        unsigned long long m_identifier; 
    }  _pageID;
}

@property (getter=_pageID, nonatomic, readonly) struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x1; } pageID;

+ (bool)supportsSecureCoding;

- (id).cxx_construct;
- (id)_initWithPageID:(struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x1; })arg1;
- (struct ObjectIdentifier<WebCore::PageIdentifierType> { unsigned long long x1; })_pageID;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;

@end
