/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKDOMDocumentParserYieldToken : NSObject {
    struct unique_ptr<WebCore::DocumentParserYieldToken, std::__1::default_delete<WebCore::DocumentParserYieldToken> > { 
        struct __compressed_pair<WebCore::DocumentParserYieldToken *, std::__1::default_delete<WebCore::DocumentParserYieldToken> > { 
            struct DocumentParserYieldToken {} *__value_; 
        } __ptr_; 
    }  _token;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithDocument:(struct Document { int (**x1)(); struct Weak<WebCore::JSDOMObject> { struct WeakImpl {} *x_2_1_1; } x2; unsigned int x3; unsigned int x4; struct ContainerNode {} *x5; struct TreeScope {} *x6; struct Node {} *x7; struct Node {} *x8; union DataUnion { struct RenderObject {} *x_9_1_1; struct NodeRareDataBase {} *x_9_1_2; } x9; struct WeakPtrFactory<WebCore::ContainerNode> { struct RefPtr<WTF::WeakPtrImpl, WTF::DumbPtrTraits<WTF::WeakPtrImpl> > { struct WeakPtrImpl {} *x_1_2_1; } x_10_1_1; } x10; struct Node {} *x11; struct Node {} *x12; struct ContainerNode {} *x13; struct reference_wrapper<WebCore::Document> { struct Document {} *x_14_1_1; } x14; struct TreeScope {} *x15; struct unique_ptr<WebCore::TreeScopeOrderedMap, std::__1::default_delete<WebCore::TreeScopeOrderedMap> > { struct __compressed_pair<WebCore::TreeScopeOrderedMap *, std::__1::default_delete<WebCore::TreeScopeOrderedMap> > { struct TreeScopeOrderedMap {} *x_1_2_1; } x_16_1_1; } x16; struct unique_ptr<WebCore::TreeScopeOrderedMap, std::__1::default_delete<WebCore::TreeScopeOrderedMap> > { struct __compressed_pair<WebCore::TreeScopeOrderedMap *, std::__1::default_delete<WebCore::TreeScopeOrderedMap> > { struct TreeScopeOrderedMap {} *x_1_2_1; } x_17_1_1; } x17; }*)arg1;

@end
