/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKSafeBrowsingBox : UIView

- (void)setSafeBrowsingBackgroundColor:(struct UIColor { Class x1; }*)arg1;

@end
