/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKUIWKTextInteractionAssistant : UIWKTextInteractionAssistant

- (void)scrollSelectionToVisible;

@end
