/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ImageCaptureCore.framework/ImageCaptureCore
 */

@interface ICAccessManager : NSObject

+ (void)addBundleIdentifierAccessingExternalMediaDevices:(id)arg1;
+ (id)bundleIdentifiersAccessingExternalMediaDevices;
+ (void)revokeBundleIdentifierAccessingExternalMediaDevices:(id)arg1;
+ (bool)validateBundleIdentifierAccessingExternalMediaDevices:(id)arg1;

@end
