/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Contacts.framework/Contacts
 */

@interface CNDowntimeWhitelist : NSObject {
    <NSObject> * _contactStoreDidChangeNotificationToken;
    CNContactStore * _store;
}

@property (readonly) <NSObject> *contactStoreDidChangeNotificationToken;
@property (readonly) CNContactStore *store;

+ (bool)isWhitelistedContact:(id)arg1;
+ (id)os_log;

- (void).cxx_destruct;
- (id)allWhitelistedContacts;
- (id)allWhitelistedHandleStrings;
- (bool)anyContactIsWhitelisted:(id)arg1;
- (id)contactStoreDidChangeNotificationToken;
- (void)dealloc;
- (id)init;
- (id)initWithContactStore:(id)arg1;
- (bool)isHandleStringWhitelisted:(id)arg1;
- (id)keys;
- (id)store;
- (id)whitelistedHandleStringsFromHandleStrings:(id)arg1;

@end
