/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEFilterDataSavedMessageHandler : NSObject {
    id /* block */  _getVerdict;
    id /* block */  _handleVerdict;
}

@property (readonly) id /* block */ getVerdict;
@property (readonly) id /* block */ handleVerdict;

- (void).cxx_destruct;
- (void)enqueueWithFlow:(id)arg1;
- (void)executeVerdictHandlerWithVerdict:(id)arg1;
- (void)executeWithFlow:(id)arg1;
- (id /* block */)getVerdict;
- (id /* block */)handleVerdict;
- (id)initWithGetVerdictBlock:(id /* block */)arg1 handleVerdictBlock:(id /* block */)arg2;

@end
