/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NetworkExtension.framework/NetworkExtension
 */

@interface NEFilterFlow : NSObject <NSCopying, NSSecureCoding> {
    NSURL * _URL;
    NSData * _crypto_signature;
    NEFilterAbsoluteVerdict * _currentVerdict;
    long long  _direction;
    int  _epid;
    NSUUID * _flowUUID;
    unsigned long long  _inBytes;
    bool  _isOpen;
    bool  _isPaused;
    bool  _isRemediationFlow;
    unsigned long long  _outBytes;
    int  _pid;
    NSObject<OS_dispatch_queue> * _queue;
    bool  _reportAtEnd;
    NSMutableArray * _savedMessageHandlerQueue;
    NSData * _sourceAppAuditToken;
    NSString * _sourceAppIdentifier;
    bool  _sourceAppIdentifierFromApp;
    NSData * _sourceAppUniqueIdentifier;
    NSString * _sourceAppVersion;
}

@property (copy) NSURL *URL;
@property (retain) NSData *crypto_signature;
@property (retain) NEFilterAbsoluteVerdict *currentVerdict;
@property long long direction;
@property int epid;
@property (copy) NSUUID *flowUUID;
@property (readonly) NSUUID *identifier;
@property unsigned long long inBytes;
@property bool isOpen;
@property bool isPaused;
@property bool isRemediationFlow;
@property unsigned long long outBytes;
@property int pid;
@property (retain) NSObject<OS_dispatch_queue> *queue;
@property bool reportAtEnd;
@property (retain) NSMutableArray *savedMessageHandlerQueue;
@property (retain) NSData *sourceAppAuditToken;
@property (copy) NSString *sourceAppIdentifier;
@property bool sourceAppIdentifierFromApp;
@property (copy) NSData *sourceAppUniqueIdentifier;
@property (copy) NSString *sourceAppVersion;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)URL;
- (void)close;
- (void)copySourceAppInfo:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)crypto_signature;
- (id)currentVerdict;
- (long long)direction;
- (void)encodeWithCoder:(id)arg1;
- (int)epid;
- (id)flowUUID;
- (id)identifier;
- (unsigned long long)inBytes;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithURL:(id)arg1 sourceAppIdentifier:(id)arg2;
- (bool)isOpen;
- (bool)isPaused;
- (bool)isRemediationFlow;
- (unsigned long long)outBytes;
- (int)pid;
- (id)queue;
- (bool)reportAtEnd;
- (id)savedMessageHandlerQueue;
- (void)setCrypto_signature:(id)arg1;
- (void)setCurrentVerdict:(id)arg1;
- (void)setDirection:(long long)arg1;
- (void)setEpid:(int)arg1;
- (void)setFlowUUID:(id)arg1;
- (void)setInBytes:(unsigned long long)arg1;
- (void)setIsOpen:(bool)arg1;
- (void)setIsPaused:(bool)arg1;
- (void)setIsRemediationFlow:(bool)arg1;
- (void)setOutBytes:(unsigned long long)arg1;
- (void)setPid:(int)arg1;
- (void)setQueue:(id)arg1;
- (void)setReportAtEnd:(bool)arg1;
- (void)setSavedMessageHandlerQueue:(id)arg1;
- (void)setSourceAppAuditToken:(id)arg1;
- (void)setSourceAppIdentifier:(id)arg1;
- (void)setSourceAppIdentifierFromApp:(bool)arg1;
- (void)setSourceAppUniqueIdentifier:(id)arg1;
- (void)setSourceAppVersion:(id)arg1;
- (void)setURL:(id)arg1;
- (id)sourceAppAuditToken;
- (id)sourceAppIdentifier;
- (bool)sourceAppIdentifierFromApp;
- (id)sourceAppUniqueIdentifier;
- (id)sourceAppVersion;

@end
