/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface _INPBRunWorkflowIntent : PBCodable <NSCopying, NSSecureCoding, _INPBRunWorkflowIntent> {
    bool  __encodeLegacyGloryData;
    struct { }  _has;
    _INPBIntentMetadata * _intentMetadata;
    _INPBArchivedObject * _stepIntentResponse;
    _INPBDataString * _workflow;
}

@property (setter=_setEncodeLegacyGloryData:, nonatomic) bool _encodeLegacyGloryData;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasIntentMetadata;
@property (nonatomic, readonly) bool hasStepIntentResponse;
@property (nonatomic, readonly) bool hasWorkflow;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) _INPBIntentMetadata *intentMetadata;
@property (nonatomic, retain) _INPBArchivedObject *stepIntentResponse;
@property (readonly) Class superclass;
@property (nonatomic, retain) _INPBDataString *workflow;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (bool)_encodeLegacyGloryData;
- (void)_setEncodeLegacyGloryData:(bool)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dictionaryRepresentation;
- (void)encodeWithCoder:(id)arg1;
- (bool)hasIntentMetadata;
- (bool)hasStepIntentResponse;
- (bool)hasWorkflow;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)intentMetadata;
- (bool)isEqual:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setIntentMetadata:(id)arg1;
- (void)setStepIntentResponse:(id)arg1;
- (void)setWorkflow:(id)arg1;
- (id)stepIntentResponse;
- (id)workflow;
- (void)writeTo:(id)arg1;

@end
