/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Intents.framework/Intents
 */

@interface INRootCodableDescription : INCodableDescription {
    NSArray * _referencedCodableDescriptions;
}

@property (setter=_setReferencedCodableDescriptions:, nonatomic, retain) NSArray *referencedCodableDescriptions;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_setReferencedCodableDescriptions:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)referencedCodableDescriptions;

@end
