/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreData.framework/CoreData
 */

@interface NSPersistentCloudKitContainerOptions : NSObject {
    NSString * _apsConnectionMachServiceName;
    NSString * _containerIdentifier;
    bool  _useEncryptedStorage;
}

@property (nonatomic, retain) NSString *apsConnectionMachServiceName;
@property (readonly, copy) NSString *containerIdentifier;
@property bool useEncryptedStorage;

- (id)apsConnectionMachServiceName;
- (id)containerIdentifier;
- (void)dealloc;
- (id)initWithContainerIdentifier:(id)arg1;
- (void)setApsConnectionMachServiceName:(id)arg1;
- (void)setUseEncryptedStorage:(bool)arg1;
- (bool)useEncryptedStorage;

@end
