/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface AR2DSkeletonDetectionPostProcessingTechnique : ARImageBasedTechnique {
    struct SkeletonJointFilter<float> { 
        struct vector<float, std::__1::allocator<float> > { 
            float *__begin_; 
            float *__end_; 
            struct __compressed_pair<float *, std::__1::allocator<float> > { 
                float *__value_; 
            } __end_cap_; 
        } m_values; 
        struct vector<float, std::__1::allocator<float> > { 
            float *__begin_; 
            float *__end_; 
            struct __compressed_pair<float *, std::__1::allocator<float> > { 
                float *__value_; 
            } __end_cap_; 
        } m_speed; 
        struct vector<double, std::__1::allocator<double> > { 
            double *__begin_; 
            double *__end_; 
            struct __compressed_pair<double *, std::__1::allocator<double> > { 
                double *__value_; 
            } __end_cap_; 
        } m_timestamps; 
        float m_smoothing; 
        float m_lowest_threshold; 
        float m_low_threshold; 
        float m_high_threshold; 
        float m_highest_threshold; 
        float m_temporal_smoothing; 
        float m_prediction_factor; 
        float m_min_smoothing; 
        double m_extrapolation_time_seconds; 
        float m_up_slope; 
        float m_down_slope; 
        float m_temporal_slope; 
    }  _extrapolationFilter2D;
    struct SkeletonJointFilter<float> { 
        struct vector<float, std::__1::allocator<float> > { 
            float *__begin_; 
            float *__end_; 
            struct __compressed_pair<float *, std::__1::allocator<float> > { 
                float *__value_; 
            } __end_cap_; 
        } m_values; 
        struct vector<float, std::__1::allocator<float> > { 
            float *__begin_; 
            float *__end_; 
            struct __compressed_pair<float *, std::__1::allocator<float> > { 
                float *__value_; 
            } __end_cap_; 
        } m_speed; 
        struct vector<double, std::__1::allocator<double> > { 
            double *__begin_; 
            double *__end_; 
            struct __compressed_pair<double *, std::__1::allocator<double> > { 
                double *__value_; 
            } __end_cap_; 
        } m_timestamps; 
        float m_smoothing; 
        float m_lowest_threshold; 
        float m_low_threshold; 
        float m_high_threshold; 
        float m_highest_threshold; 
        float m_temporal_smoothing; 
        float m_prediction_factor; 
        float m_min_smoothing; 
        double m_extrapolation_time_seconds; 
        float m_up_slope; 
        float m_down_slope; 
        float m_temporal_slope; 
    }  _extrapolationFilter2DForLiftingData;
    AR2DSkeletonDetectionPostProcessGPU * _postProcessorGPU;
    AR2DSkeletonRawEspressoResult * _previousRawEspressoResult;
    NSObject<OS_dispatch_queue> * _processingQueue;
}

@property (nonatomic, retain) AR2DSkeletonRawEspressoResult *previousRawEspressoResult;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)init;
- (id)previousRawEspressoResult;
- (id)processData:(id)arg1;
- (double)requiredTimeInterval;
- (void)setPreviousRawEspressoResult:(id)arg1;

@end
