/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface AR2DSkeletonRawEspressoResult : NSObject <ARResultData> {
    ARImageData * _imageDataForNeuralNetwork;
    ARImageData * _inputImageData;
    unsigned long long  _numberOfOutputTensors;
    void * _outputTensors;
    struct CGSize { 
        double width; 
        double height; 
    }  _regionOfInterest;
    long long  _rotationNeeded;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) ARImageData *imageDataForNeuralNetwork;
@property (nonatomic, retain) ARImageData *inputImageData;
@property (nonatomic) unsigned long long numberOfOutputTensors;
@property (nonatomic) void*outputTensors;
@property (nonatomic) struct CGSize { double x1; double x2; } regionOfInterest;
@property (nonatomic) long long rotationNeeded;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)imageDataForNeuralNetwork;
- (id)inputImageData;
- (unsigned long long)numberOfOutputTensors;
- (void*)outputTensors;
- (struct CGSize { double x1; double x2; })regionOfInterest;
- (long long)rotationNeeded;
- (void)setImageDataForNeuralNetwork:(id)arg1;
- (void)setInputImageData:(id)arg1;
- (void)setNumberOfOutputTensors:(unsigned long long)arg1;
- (void)setOutputTensors:(void*)arg1;
- (void)setRegionOfInterest:(struct CGSize { double x1; double x2; })arg1;
- (void)setRotationNeeded:(long long)arg1;

@end
