/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARCoachingHeuristicAnyPlane : ARCoachingHeuristic

- (long long)requirements;
- (void)updateWithFrame:(id)arg1;

@end
