/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARCompositeSignaler : NSObject {
    NSCondition * _compositeCondition;
    _Atomic unsigned long long  _lastRenderCount;
    NSCondition * _renderCondition;
    _Atomic unsigned long long  _renderCount;
}

- (void).cxx_destruct;
- (id)init;
- (void)signalCompositorThread;
- (void)signalRenderThread;
- (void)signalRenderThreadWhenPaused;
- (void)waitCompositorThread;
- (void)waitRenderThreadUsingBlock:(id /* block */)arg1;

@end
