/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARCompositeStats : NSObject {
    double  _compositeEnd;
    double  _compositeEndCPU;
    double  _compositePresent;
    double  _compositeStart;
    double  _compositeStartTarget;
    double  _compositeStartTargetTimeBeforeVsyncEnd;
    double  _compositeTime;
    double  _compositeTimeCPU;
    unsigned long long  _vsyncCount;
    double  _vsyncEnd;
    double  _vsyncStart;
    double  _vsyncTime;
    double  _vsyncTimeActual;
}

@property (nonatomic, readonly) double compositeEnd;
@property (nonatomic, readonly) double compositeEndCPU;
@property (nonatomic) double compositePresent;
@property (nonatomic, readonly) double compositeStart;
@property (nonatomic) double compositeStartTarget;
@property (nonatomic) double compositeStartTargetTimeBeforeVsyncEnd;
@property (nonatomic, readonly) double compositeTime;
@property (nonatomic, readonly) double compositeTimeCPU;
@property (nonatomic, readonly) unsigned long long vsyncCount;
@property (nonatomic, readonly) double vsyncEnd;
@property (nonatomic, readonly) double vsyncStart;
@property (nonatomic, readonly) double vsyncTime;
@property (nonatomic, readonly) double vsyncTimeActual;

- (double)compositeEnd;
- (double)compositeEndCPU;
- (double)compositePresent;
- (double)compositeStart;
- (double)compositeStartTarget;
- (double)compositeStartTargetTimeBeforeVsyncEnd;
- (double)compositeTime;
- (double)compositeTimeCPU;
- (id)description;
- (void)endComposite:(double)arg1;
- (void)endCompositeCPU;
- (void)setCompositePresent:(double)arg1;
- (void)setCompositeStartTarget:(double)arg1;
- (void)setCompositeStartTargetTimeBeforeVsyncEnd:(double)arg1;
- (void)startComposite;
- (void)tickComposite:(id)arg1 vsyncCounter:(unsigned long long)arg2;
- (unsigned long long)vsyncCount;
- (double)vsyncEnd;
- (double)vsyncStart;
- (double)vsyncTime;
- (double)vsyncTimeActual;

@end
