/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARCriticalTimer : NSObject {
    struct __CFMachPort { } * _cfPort;
    unsigned int  _timerPort;
    id /* block */  _userCallback;
}

- (void).cxx_destruct;
- (void)cancel;
- (void)completionHandler;
- (void)dealloc;
- (id)init;
- (void)start:(double)arg1 withCallback:(id /* block */)arg2;

@end
