/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface AREspressoInputBuffer : NSObject {
    ARImageData * _imageDataForNeuralNetwork;
    bool  _isValid;
    ARImageData * _originalImageData;
    struct CGSize { 
        double width; 
        double height; 
    }  _regionOfInterest;
    long long  _rotationOfResultTensor;
}

@property (retain) ARImageData *imageDataForNeuralNetwork;
@property (nonatomic) bool isValid;
@property (retain) ARImageData *originalImageData;
@property (nonatomic) struct CGSize { double x1; double x2; } regionOfInterest;
@property (nonatomic) long long rotationOfResultTensor;

- (void).cxx_destruct;
- (id)imageDataForNeuralNetwork;
- (bool)isValid;
- (id)originalImageData;
- (struct CGSize { double x1; double x2; })regionOfInterest;
- (long long)rotationOfResultTensor;
- (void)setImageDataForNeuralNetwork:(id)arg1;
- (void)setIsValid:(bool)arg1;
- (void)setOriginalImageData:(id)arg1;
- (void)setRegionOfInterest:(struct CGSize { double x1; double x2; })arg1;
- (void)setRotationOfResultTensor:(long long)arg1;

@end
