/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARExposureLightEstimationTechnique : ARTechnique {
    float  _lightIntensity;
    NSObject<OS_dispatch_semaphore> * _resultSemaphore;
    struct ExponentialSmoother<float> { 
        struct optional<float> { 
            union { 
                BOOL __null_state_; 
                float __val_; 
            } ; 
            bool __engaged_; 
        } state; 
    }  _smoother;
    float  _temperature;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)init;
- (id)processData:(id)arg1;
- (void)requestResultDataAtTimestamp:(double)arg1 context:(id)arg2;
- (unsigned long long)requiredSensorDataTypes;

@end
