/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARImageSensorSettings : NSObject <NSCopying> {
    bool  _autoFocusEnabled;
    bool  _enabled;
    bool  _geometricDistortionCorrectionEnabled;
    float  _maxGainOverride;
    NSString * _metaData;
    bool  _mirrorVideoOutput;
    ARVideoFormat * _videoFormat;
    bool  _visionDataOutputEnabled;
    NSDictionary * _visionDataOutputParameters;
}

@property (nonatomic) bool autoFocusEnabled;
@property (getter=isEnabled, nonatomic) bool enabled;
@property (nonatomic) bool geometricDistortionCorrectionEnabled;
@property (nonatomic) float maxGainOverride;
@property (nonatomic, copy) NSString *metaData;
@property (nonatomic) bool mirrorVideoOutput;
@property (nonatomic, retain) ARVideoFormat *videoFormat;
@property (nonatomic) bool visionDataOutputEnabled;
@property (nonatomic, retain) NSDictionary *visionDataOutputParameters;

- (void).cxx_destruct;
- (bool)autoFocusEnabled;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (bool)geometricDistortionCorrectionEnabled;
- (unsigned long long)hash;
- (id)initWithVideoFormat:(id)arg1;
- (bool)isEnabled;
- (bool)isEqual:(id)arg1;
- (float)maxGainOverride;
- (id)metaData;
- (bool)mirrorVideoOutput;
- (void)setAutoFocusEnabled:(bool)arg1;
- (void)setEnabled:(bool)arg1;
- (void)setGeometricDistortionCorrectionEnabled:(bool)arg1;
- (void)setMaxGainOverride:(float)arg1;
- (void)setMetaData:(id)arg1;
- (void)setMirrorVideoOutput:(bool)arg1;
- (void)setVideoFormat:(id)arg1;
- (void)setVisionDataOutputEnabled:(bool)arg1;
- (void)setVisionDataOutputParameters:(id)arg1;
- (id)videoFormat;
- (bool)visionDataOutputEnabled;
- (id)visionDataOutputParameters;

@end
