/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARMLDepthData : NSObject <ARResultData> {
    struct __CVBuffer { } * _depthBuffer;
    double  _timestamp;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly) struct __CVBuffer { }*depthBuffer;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) double timestamp;

- (void)dealloc;
- (struct __CVBuffer { }*)depthBuffer;
- (id)description;
- (id)initWithTimestamp:(double)arg1 depthBuffer:(struct __CVBuffer { }*)arg2;
- (double)timestamp;

@end
