/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPresentationDisplayLinkHelper : NSObject {
    ARPresentation * _arpresentation;
}

- (void).cxx_destruct;
- (void)callback:(id)arg1;
- (id)initWithARPresentation:(id)arg1;

@end
