/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPresentationThermalPolicyManager : NSObject {
    NSDictionary * _thermalPolicyMap;
}

@property (nonatomic, retain) NSDictionary *thermalPolicyMap;

+ (double)minimumThermalHysterisWindow;
+ (id)sharedInstance;
+ (bool)thermalMitigationEnabled;

- (void).cxx_destruct;
- (long long)_cameraFPSFactoringInTechniques:(id)arg1 condition:(id)arg2;
- (long long)_cameraFPSOverride;
- (bool)_containsTrackingTechnique:(Class)arg1 inTechniques:(id)arg2;
- (id)_generateThermalPolicyMap;
- (long long)_minCameraFPSForImageTrackingInDeviceCondition:(id)arg1;
- (id)_policyForCondition:(id)arg1;
- (void)_updateBackCameraConfigIfNeeded:(id)arg1 techniques:(id)arg2 condition:(id)arg3;
- (id)init;
- (id)policyForCondition:(id)arg1 andTechniques:(id)arg2;
- (void)setThermalPolicyMap:(id)arg1;
- (id)thermalPolicyMap;

@end
