/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPredictedSample : NSObject {
    ARPredictedPose * _compositeEndPose;
    ARPredictedPose * _compositeStartPose;
    ARPredictedPose * _renderPose;
    ARPredictedPose * _screenDrawingPose;
}

@property (nonatomic, retain) ARPredictedPose *compositeEndPose;
@property (nonatomic, retain) ARPredictedPose *compositeStartPose;
@property (nonatomic, retain) ARPredictedPose *renderPose;
@property (nonatomic, retain) ARPredictedPose *screenDrawingPose;

- (void).cxx_destruct;
- (id)compositeEndPose;
- (id)compositeStartPose;
- (id)description;
- (id)renderPose;
- (id)screenDrawingPose;
- (void)setCompositeEndPose:(id)arg1;
- (void)setCompositeStartPose:(id)arg1;
- (void)setRenderPose:(id)arg1;
- (void)setScreenDrawingPose:(id)arg1;

@end
