/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPresentationStats : NSObject {
    double  _averageCompositeTime;
    double  _averageCompositeTimePercent;
    double  _averageRenderTime;
    double  _averageRenderTimePercent;
    double  _averageTotalTime;
    double  _averageTotalTimePercent;
    long long  _mode;
    NSArray * _predictedSamples;
    double  _vsyncTime;
}

@property (nonatomic) double averageCompositeTime;
@property (nonatomic) double averageCompositeTimePercent;
@property (nonatomic) double averageRenderTime;
@property (nonatomic) double averageRenderTimePercent;
@property (nonatomic) double averageTotalTime;
@property (nonatomic) double averageTotalTimePercent;
@property (nonatomic) long long mode;
@property (nonatomic, retain) NSArray *predictedSamples;
@property (nonatomic) double vsyncTime;

- (void).cxx_destruct;
- (id)_predictedSamplesDescription;
- (id)asDictionary;
- (double)averageCompositeTime;
- (double)averageCompositeTimePercent;
- (double)averageRenderTime;
- (double)averageRenderTimePercent;
- (double)averageTotalTime;
- (double)averageTotalTimePercent;
- (long long)mode;
- (id)predictedSamples;
- (void)setAverageCompositeTime:(double)arg1;
- (void)setAverageCompositeTimePercent:(double)arg1;
- (void)setAverageRenderTime:(double)arg1;
- (void)setAverageRenderTimePercent:(double)arg1;
- (void)setAverageTotalTime:(double)arg1;
- (void)setAverageTotalTimePercent:(double)arg1;
- (void)setMode:(long long)arg1;
- (void)setPredictedSamples:(id)arg1;
- (void)setVsyncTime:(double)arg1;
- (double)vsyncTime;

@end
