/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPredictionStats : NSObject {
    NSMutableArray * _predictedSamples;
    long long  _predictedSamplesCount;
    long long  _predictedSamplesIndex;
    ARPredictedSamplesQueue * _predictedSamplesQueue;
    NSObject<OS_dispatch_queue> * _predictionQueue;
    ARSession * _session;
    ARCriticalTimer * _sleepTimer;
}

@property (nonatomic, retain) NSMutableArray *predictedSamples;
@property (nonatomic) long long predictedSamplesCount;
@property (nonatomic) long long predictedSamplesIndex;
@property (nonatomic, retain) ARPredictedSamplesQueue *predictedSamplesQueue;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *predictionQueue;
@property (nonatomic) ARSession *session;
@property (nonatomic, retain) ARCriticalTimer *sleepTimer;

+ (bool)enabled;

- (void).cxx_destruct;
- (void)_fillSlotWithFrameNumber:(unsigned long long)arg1 type:(unsigned long long)arg2 pose:(id)arg3 timeStamp:(double)arg4;
- (long long)_findSlotForFrameNumber:(unsigned long long)arg1;
- (long long)_getIndexFromFrameNumber:(unsigned long long)arg1;
- (bool)_isPoseValid:(id)arg1;
- (bool)_isSlotIndexValid:(long long)arg1;
- (bool)_isTimeStamp:(double)arg1 withinStart:(double)arg2 andEnd:(double)arg3;
- (long long)_nextIndex:(long long)arg1;
- (long long)_previousIndex:(long long)arg1;
- (void)_resetSlotForSlotIndex:(long long)arg1;
- (void)_schedulePredictionAtTime:(double)arg1 frameNumber:(unsigned long long)arg2;
- (bool)_slotIndex:(long long)arg1 hasFrameNumber:(unsigned long long)arg2;
- (void)drawablePresentedAtTime:(double)arg1 frameNumber:(unsigned long long)arg2 presentTime:(double)arg3 vsyncTime:(double)arg4;
- (id)init;
- (void)predictedCompositingEndPose:(id)arg1 frameNumber:(unsigned long long)arg2 timeStamp:(double)arg3;
- (void)predictedCompositingStartPose:(id)arg1 frameNumber:(unsigned long long)arg2 timeStamp:(double)arg3;
- (void)predictedRenderingPose:(id)arg1 frameNumber:(unsigned long long)arg2 timeStamp:(double)arg3;
- (id)predictedSamples;
- (long long)predictedSamplesCount;
- (long long)predictedSamplesIndex;
- (id)predictedSamplesQueue;
- (id)predictionQueue;
- (id)samples;
- (id)session;
- (void)setPredictedSamples:(id)arg1;
- (void)setPredictedSamplesCount:(long long)arg1;
- (void)setPredictedSamplesIndex:(long long)arg1;
- (void)setPredictedSamplesQueue:(id)arg1;
- (void)setPredictionQueue:(id)arg1;
- (void)setSession:(id)arg1;
- (void)setSleepTimer:(id)arg1;
- (id)sleepTimer;

@end
