/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPresentationFramePool : NSObject {
    <MTLSharedEvent> * _applicationEvent;
    bool  _areFramesValid;
    <MTLCommandQueue> * _commandQueue;
    <MTLSharedEvent> * _compositorEvent;
    NSCondition * _condition;
    ARPresentationDescriptor * _descriptor;
    ARPresentationDisplay * _display;
    int  _eyeCount;
    NSArray * _eyes;
    NSMutableArray * _forwardFlow;
    unsigned long long  _frameNumberIndex;
    NSMutableArray * _framePool;
    unsigned long long  _framePoolCount;
    unsigned long long  _framePoolIndex;
    NSMutableArray * _frameStack;
    unsigned long long  _frameStackCount;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    <MTLTexture> * _msaaColor;
    <MTLTexture> * _msaaDepth;
    struct CGSize { 
        double width; 
        double height; 
    }  _textureSize;
}

@property (nonatomic, copy) ARPresentationDescriptor *descriptor;
@property (nonatomic, copy) ARPresentationDisplay *display;
@property (nonatomic, retain) NSMutableArray *forwardFlow;

- (void).cxx_destruct;
- (void)_addPresentationFrame;
- (id)_createMultisampleTexture:(unsigned long long)arg1 pixelFormat:(unsigned long long)arg2 textureSize:(struct CGSize { double x1; double x2; })arg3;
- (id)_createTexture:(unsigned long long)arg1 textureSize:(struct CGSize { double x1; double x2; })arg2 name:(id)arg3;
- (void)_deleteMSAATextures;
- (id)_findPresentationFrame:(unsigned long long)arg1;
- (bool)_hasPresentationFrameToRender;
- (void)_invalidateFrames;
- (void)_lock_deleteForwardFlowBuffer;
- (bool)_lock_hasPresentationFrameToRender;
- (void)_lock_updateForwardFlowBuffer:(id)arg1;
- (void)_lock_updateMSAATextures:(id)arg1;
- (void)_signalPresentationFrameToRender;
- (struct { double x1; double x2; double x3; double x4; double x5; double x6; })_snapViewport:(struct { double x1; double x2; double x3; double x4; double x5; double x6; })arg1;
- (void)_updateRenderPassDescriptor:(id)arg1;
- (void)_updateViewports;
- (void)allocateTextures;
- (id)descriptor;
- (id)display;
- (id)findPresentationFrame:(unsigned long long)arg1;
- (id)findPresentationFrameToComposite:(unsigned long long)arg1;
- (id)findPresentationFrameToPresent;
- (id)forwardFlow;
- (id)initWithCommandQueue:(id)arg1 compositorEvent:(id)arg2 applicationEvent:(id)arg3;
- (id)lastFrameRendered;
- (id)mainRenderPassDescriptor:(id)arg1 zfar:(double)arg2;
- (id)makePresentationFrame:(id)arg1 frameNumber:(unsigned long long)arg2;
- (void)setDescriptor:(id)arg1;
- (void)setDisplay:(id)arg1;
- (void)setForwardFlow:(id)arg1;
- (void)skipComposite:(unsigned long long)arg1;
- (void)updateWarpPose:(id)arg1 scanoutStart:(id)arg2 scanoutEnd:(id)arg3;
- (void)waitForPresentationFrameToRenderUsingBlock:(id /* block */)arg1;

@end
