/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPredictedSamplesQueue : NSObject {
    NSMutableArray * _allSamples;
    int  _capacity;
}

@property (nonatomic, retain) NSMutableArray *allSamples;
@property (nonatomic) int capacity;

- (void).cxx_destruct;
- (void)add:(id)arg1;
- (id)allSamples;
- (int)capacity;
- (id)description;
- (id)init;
- (id)samples;
- (void)setAllSamples:(id)arg1;
- (void)setCapacity:(int)arg1;

@end
