/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPresentationFrame : NSObject {
    <MTLSharedEvent> * _applicationEvent;
    <MTLSharedEvent> * _compositorEvent;
    void _depthHints;
    ARFrame * _frame;
    unsigned long long  _frameNumber;
    ARRenderStats * _frameStatsRender;
    NSArray * _presentationTargets;
    double  _timestamp;
    struct { 
        /* Warning: Unrecognized filer type: ']' using 'void*' */ void*columns[4]; 
    }  _transform;
    unsigned long long  _waitFrameNumber;
    unsigned long long  _waitNumber;
}

@property (nonatomic, readonly) <MTLSharedEvent> *applicationEvent;
@property (nonatomic, readonly) <MTLSharedEvent> *compositorEvent;
@property (nonatomic) void depthHints;
@property (nonatomic, retain) ARFrame *frame;
@property (nonatomic) unsigned long long frameNumber;
@property (nonatomic, retain) ARRenderStats *frameStatsRender;
@property (nonatomic, readonly) NSArray *presentationTargets;
@property (nonatomic) double timestamp;
@property (nonatomic) struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; } transform;
@property (nonatomic) unsigned long long waitFrameNumber;
@property (nonatomic) unsigned long long waitNumber;

- (void).cxx_destruct;
- (id)applicationEvent;
- (id)compositorEvent;
- (void)depthHints;
- (id)description;
- (id)frame;
- (unsigned long long)frameNumber;
- (id)frameStatsRender;
- (id)initWithPresentationTargets:(id)arg1 compositorEvent:(id)arg2 applicationEvent:(id)arg3;
- (id)presentationTargetForEyeLocation:(long long)arg1;
- (id)presentationTargets;
- (void)setDepthHints;
- (void)setFrame:(id)arg1;
- (void)setFrameNumber:(unsigned long long)arg1;
- (void)setFrameStatsRender:(id)arg1;
- (void)setTimestamp:(double)arg1;
- (void)setTransform:(struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; })arg1;
- (void)setWaitFrameNumber:(unsigned long long)arg1;
- (void)setWaitNumber:(unsigned long long)arg1;
- (void)signalAfterFinishingRender:(id)arg1;
- (double)timestamp;
- (struct { /* Warning: Unrecognized filer type: ']' using 'void*' */ void*x1[4]; })transform;
- (void)waitBeforeStartingRender:(id)arg1;
- (unsigned long long)waitFrameNumber;
- (unsigned long long)waitNumber;

@end
