/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARPresentationThermalPolicy : NSObject {
    NSMutableDictionary * _cameraConfigurations;
}

@property (readonly) NSMutableDictionary *cameraConfigurations;

- (void).cxx_destruct;
- (id)_keyForType:(id)arg1 position:(long long)arg2;
- (void)addCameraConfig:(id)arg1;
- (id)cameraConfigForDeviceType:(id)arg1 position:(long long)arg2;
- (id)cameraConfigurations;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)init;
- (void)updateCameraConfig:(id)arg1;

@end
