/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARSinglePassRenderer : NSObject {
    ARPresentation * _presentation;
    SCNRenderer * _renderer;
}

@property (nonatomic) ARPresentation *presentation;
@property (nonatomic, readonly) SCNRenderer *sceneRenderer;

- (void).cxx_destruct;
- (id)initWithSCNRenderer:(id)arg1;
- (id)presentation;
- (void)renderFrame:(id)arg1;
- (id)sceneRenderer;
- (void)setPresentation:(id)arg1;

@end
