/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARStarBoardViewController : UIViewController {
    UIView * _echelonBox;
    ARPresentationDescriptor * _presentationDescriptor;
    ARStarBoardPresentationView * _presentationView;
    UILabel * _statisticsLabel;
    NSString * _statisticsString;
}

@property (nonatomic, readonly) CAMetalLayer *presentationLayer;
@property (nonatomic, retain) NSString *statisticsString;

- (void).cxx_destruct;
- (void)loadView;
- (long long)preferredInterfaceOrientationForPresentation;
- (id)presentationLayer;
- (void)setStatisticsString:(id)arg1;
- (void)setupEchelonHUDPlacement:(unsigned long long)arg1;
- (void)setupStatisticsWithView:(id)arg1;
- (id)statisticsString;
- (unsigned long long)supportedInterfaceOrientations;
- (void)updateDescriptor:(id)arg1;
- (void)updateEchelonHUDPlacement:(unsigned long long)arg1;
- (void)viewDidLayoutSubviews;

@end
