/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARStarBoardSceneManager : NSObject {
    NSHashTable * _observers;
}

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)addSceneObserver:(id)arg1;
- (id)init;
- (void)starBoardSceneConnected:(id)arg1;
- (void)starBoardSceneDisconnected:(id)arg1;

@end
