/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARStarData : NSObject <ARSensorData, NSSecureCoding> {
    SRHMEConfig * _config;
    long long  _mode;
    double  _timestamp;
}

@property (nonatomic, readonly) SRHMEConfig *config;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long mode;
@property (readonly) Class superclass;
@property (nonatomic) double timestamp;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)config;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSession:(id)arg1;
- (long long)mode;
- (void)setMode:(long long)arg1;
- (void)setTimestamp:(double)arg1;
- (double)timestamp;

@end
