/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARWorldTrackingConfiguration : ARConfiguration {
    bool  _automaticImageScaleEstimationEnabled;
    bool  _collaborationEnabled;
    bool  _deliverRawSceneUnderstandingResults;
    NSSet * _detectionImages;
    NSSet * _detectionObjects;
    long long  _environmentTexturing;
    ARWorldMap * _initialWorldMap;
    long long  _maximumNumberOfTrackedImages;
    double  _minVergenceAngle;
    bool  _mlModelEnabled;
    unsigned long long  _planeDetection;
    bool  _relocalizationEnabled;
    bool  _shouldUseSuperWideIfAvailable;
    bool  _skeletonDetectionEnabled;
    NSString * _slamConfiguration;
    bool  _userFaceTrackingEnabled;
    bool  _wantsHDREnvironmentTextures;
}

@property (getter=isAutoFocusEnabled, nonatomic) bool autoFocusEnabled;
@property (nonatomic) bool automaticImageScaleEstimationEnabled;
@property (getter=isCollaborationEnabled, nonatomic) bool collaborationEnabled;
@property (nonatomic) bool deliverRawSceneUnderstandingResults;
@property (nonatomic, copy) NSSet *detectionImages;
@property (nonatomic, copy) NSSet *detectionObjects;
@property (nonatomic) long long environmentTexturing;
@property (nonatomic, readonly) ARImageSensorSettings *imageSensorSettingsForSuperWide;
@property (nonatomic, retain) ARWorldMap *initialWorldMap;
@property (nonatomic) long long maximumNumberOfTrackedImages;
@property (nonatomic) double minVergenceAngle;
@property (getter=isMLModelEnabled, nonatomic) bool mlModelEnabled;
@property (nonatomic) unsigned long long planeDetection;
@property (nonatomic) bool relocalizationEnabled;
@property (nonatomic) bool shouldUseSuperWideIfAvailable;
@property (getter=isSkeletonDetectionEnabled, nonatomic) bool skeletonDetectionEnabled;
@property (nonatomic, copy) NSString *slamConfiguration;
@property (getter=userFaceTrackingEnabled, nonatomic) bool userFaceTrackingEnabled;
@property (nonatomic) bool wantsHDREnvironmentTextures;

+ (bool)isSupported;
+ (id)new;
+ (id)supportedVideoFormats;
+ (id)supportedVideoFormatsForSuperWide;
+ (id)supportedVideoFormatsForUserFaceTracking;
+ (bool)supportsFrameSemantics:(unsigned long long)arg1;
+ (bool)supportsFrontCameraFaceAnchors;
+ (bool)supportsUserFaceTracking;

- (void).cxx_destruct;
- (id)_trackingOptions;
- (bool)automaticImageScaleEstimationEnabled;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)createTechniquesWithParallelTechniques:(id)arg1 serialTechniques:(id)arg2;
- (bool)deliverRawSceneUnderstandingResults;
- (id)description;
- (id)detectionImages;
- (id)detectionObjects;
- (long long)environmentTexturing;
- (id)imageSensorSettings;
- (id)imageSensorSettingsForSuperWide;
- (id)imageSensorSettingsForUserFaceTracking;
- (id)init;
- (id)initialWorldMap;
- (bool)isCollaborationEnabled;
- (bool)isEqual:(id)arg1;
- (bool)isMLModelEnabled;
- (bool)isSkeletonDetectionEnabled;
- (long long)maximumNumberOfTrackedImages;
- (double)minVergenceAngle;
- (id)parentImageSensorSettings;
- (unsigned long long)planeDetection;
- (bool)relocalizationEnabled;
- (id)secondaryTechniques;
- (void)setAutomaticImageScaleEstimationEnabled:(bool)arg1;
- (void)setCollaborationEnabled:(bool)arg1;
- (void)setDeliverRawSceneUnderstandingResults:(bool)arg1;
- (void)setDetectionImages:(id)arg1;
- (void)setDetectionObjects:(id)arg1;
- (void)setEnvironmentTexturing:(long long)arg1;
- (void)setFrontCameraFaceAnchorsEnabled:(bool)arg1;
- (void)setInitialWorldMap:(id)arg1;
- (void)setMaximumNumberOfTrackedImages:(long long)arg1;
- (void)setMinVergenceAngle:(double)arg1;
- (void)setMlModelEnabled:(bool)arg1;
- (void)setPlaneDetection:(unsigned long long)arg1;
- (void)setRelocalizationEnabled:(bool)arg1;
- (void)setShouldUseSuperWideIfAvailable:(bool)arg1;
- (void)setSkeletonDetectionEnabled:(bool)arg1;
- (void)setSlamConfiguration:(id)arg1;
- (void)setUserFaceTrackingEnabled:(bool)arg1;
- (void)setWantsHDREnvironmentTextures:(bool)arg1;
- (bool)shouldEnableVisionDataForImageSensorSettings:(id)arg1;
- (bool)shouldUseSuperWide;
- (bool)shouldUseSuperWideIfAvailable;
- (id)slamConfiguration;
- (bool)userFaceTrackingEnabled;
- (bool)wantsHDREnvironmentTextures;

@end
