/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ARKit.framework/ARKit
 */

@interface ARWorldTrackingOptions : NSObject <NSCopying> {
    NSMutableDictionary * _activeVideoFormatsMap;
    NSObject<OS_dispatch_semaphore> * _activeVideoFormatsSemaphore;
    bool  _collaborationEnabled;
    bool  _deliverRawSceneUnderstandingResults;
    bool  _deterministicMode;
    NSString * _deviceModel;
    ARImageSensorSettings * _imageSensorSettings;
    ARImageSensorSettings * _imageSensorSettingsForSuperWide;
    ARWorldMap * _initialWorldMap;
    double  _minVergenceAngle;
    bool  _mlModelEnabled;
    unsigned long long  _planeDetection;
    bool  _relocalizationEnabled;
    NSString * _slamConfiguration;
}

@property (nonatomic, readonly) NSDictionary *activeVideoFormatsMap;
@property (getter=isCollaborationEnabled, nonatomic) bool collaborationEnabled;
@property (nonatomic) bool deliverRawSceneUnderstandingResults;
@property (nonatomic) bool deterministicMode;
@property (nonatomic, copy) NSString *deviceModel;
@property (nonatomic, readonly) NSDictionary *dictionary;
@property (nonatomic, copy) ARImageSensorSettings *imageSensorSettings;
@property (nonatomic, copy) ARImageSensorSettings *imageSensorSettingsForSuperWide;
@property (nonatomic, copy) ARWorldMap *initialWorldMap;
@property (nonatomic) double minVergenceAngle;
@property (nonatomic) bool mlModelEnabled;
@property (nonatomic) unsigned long long planeDetection;
@property (nonatomic) bool relocalizationEnabled;
@property (nonatomic, copy) NSString *slamConfiguration;

- (void).cxx_destruct;
- (id)activeVideoFormatsMap;
- (unsigned int)cameraIdForCaptureDeviceType:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (int)createSLAMCalibration:(struct CV3DSLAMCalibration {}**)arg1;
- (void)createSLAMConfig:(struct CV3DSLAMConfig {}**)arg1;
- (bool)deliverRawSceneUnderstandingResults;
- (bool)deterministicMode;
- (id)deviceModel;
- (id)dictionary;
- (id)imageSensorSettings;
- (id)imageSensorSettingsForSuperWide;
- (id)init;
- (id)initWithImageSensorSettings:(id)arg1;
- (id)initialWorldMap;
- (bool)isCollaborationEnabled;
- (bool)isEqual:(id)arg1;
- (double)minVergenceAngle;
- (bool)mlModelEnabled;
- (unsigned long long)planeDetection;
- (bool)relocalizationEnabled;
- (void)setCollaborationEnabled:(bool)arg1;
- (void)setDeliverRawSceneUnderstandingResults:(bool)arg1;
- (void)setDeterministicMode:(bool)arg1;
- (void)setDeviceModel:(id)arg1;
- (void)setImageSensorSettings:(id)arg1;
- (void)setImageSensorSettingsForSuperWide:(id)arg1;
- (void)setInitialWorldMap:(id)arg1;
- (void)setMinVergenceAngle:(double)arg1;
- (void)setMlModelEnabled:(bool)arg1;
- (void)setPlaneDetection:(unsigned long long)arg1;
- (void)setRelocalizationEnabled:(bool)arg1;
- (void)setSlamConfiguration:(id)arg1;
- (int)setupCameraCalibration:(struct CV3DSLAMCalibration {}**)arg1 forImageSensorSettings:(id)arg2 deviceModel:(int)arg3;
- (bool)shouldUseSuperWide;
- (id)slamConfiguration;
- (void)updateCameraMap;

@end
