/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftNetwork.dylib
 */

@interface _TtCC7Network13_NWConnection14ContentContext : Swift._SwiftObject {
    void antecedent;
    void expirationMilliseconds;
    void identifier;
    void isFinal;
    void nw;
    void relativePriority;
}

@end
