/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftNetwork.dylib
 */

@interface Network._NWListener : Swift._SwiftObject {
    void _newConnectionHandler;
    void _queue;
    void _service;
    void _serviceRegistrationUpdateHandler;
    void _state;
    void _stateUpdateHandler;
    void nw;
    void parameters;
}

@end
