/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftNetwork.dylib
 */

@interface Network._NWPathMonitor : Swift._SwiftObject {
    void _pathUpdateHandler;
    void _queue;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  currentPath;
    void nw;
}

@end
