/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftNetwork.dylib
 */

@interface Network.NWBrowser : Swift._SwiftObject {
    void browseResults;
    void browseResultsChangedHandler;
    void changes;
    void descriptor;
    void nw;
    void parameters;
    void queue;
    void state;
    void stateUpdateHandler;
}

@end
