/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftFoundation.dylib
 */

@interface _TtCE10FoundationCSo7NSTimer14TimerPublisher : Swift._SwiftObject {
    void $__lazy_storage_$_routingSubscription;
    void interval;
    void mode;
    void options;
    void runLoop;
    void tolerance;
}

@end
