/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNGenerateObjectnessBasedSaliency544x544Detector : VNGenerateObjectnessBasedSaliencyDetector

- (id)espressoModelFileNameForConfigurationOptions:(id)arg1;

@end
