/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKConditionRecord : HKMedicalRecord <HDCoding, HKConceptIndexable, NSCopying, NSSecureCoding> {
    HKInspectableValue * _abatement;
    NSString * _asserter;
    NSArray * _bodySites;
    NSArray * _bodySitesCodings;
    HKConcept * _category;
    NSArray * _categoryCodings;
    HKConcept * _clinicalStatus;
    HKMedicalCoding * _clinicalStatusCoding;
    HKConcept * _condition;
    NSArray * _conditionCodings;
    HKInspectableValue * _onset;
    HKMedicalDate * _recordedDate;
    HKConcept * _severity;
    NSArray * _severityCodings;
    HKConcept * _verificationStatus;
    HKMedicalCoding * _verificationStatusCoding;
}

@property (readonly) NSUUID *UUID;
@property (readonly, copy) HKInspectableValue *abatement;
@property (readonly, copy) NSString *asserter;
@property (readonly, copy) NSArray *bodySites;
@property (readonly, copy) NSArray *bodySitesCodings;
@property (readonly, copy) HKConcept *category;
@property (readonly, copy) NSArray *categoryCodings;
@property (readonly, copy) HKConcept *clinicalStatus;
@property (readonly, copy) HKMedicalCoding *clinicalStatusCoding;
@property (readonly, copy) HKConcept *condition;
@property (readonly, copy) NSArray *conditionCodings;
@property (readonly, copy) HKConditionRecordType *conditionRecordType;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSLocale *locale;
@property (readonly, copy) HKInspectableValue *onset;
@property (readonly, copy) HKMedicalDate *recordedDate;
@property (readonly, copy) HKConcept *severity;
@property (readonly, copy) NSArray *severityCodings;
@property (readonly) Class superclass;
@property (readonly, copy) HKConcept *verificationStatus;
@property (readonly, copy) HKMedicalCoding *verificationStatusCoding;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)_newConditionRecordWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 sortDate:(id)arg10 conditionCodings:(id)arg11 categoryCodings:(id)arg12 asserter:(id)arg13 abatement:(id)arg14 onset:(id)arg15 recordedDate:(id)arg16 clinicalStatusCoding:(id)arg17 verificationStatusCoding:(id)arg18 severityCodings:(id)arg19 bodySitesCodings:(id)arg20 config:(id /* block */)arg21;
+ (id)bodySitesCodingsPreferredSystems;
+ (id)cachedConceptRelationshipKeyPaths;
+ (id)categoryCodingsPreferredSystems;
+ (id)clinicalStatusCodingPreferredSystems;
+ (id)conditionCodingsPreferredSystems;
+ (id)conditionRecordWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 conditionCodings:(id)arg10 categoryCodings:(id)arg11 asserter:(id)arg12 abatement:(id)arg13 onset:(id)arg14 recordedDate:(id)arg15 clinicalStatusCoding:(id)arg16 verificationStatusCoding:(id)arg17 severityCodings:(id)arg18 bodySitesCodings:(id)arg19;
+ (id)conditionRecordWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 sortDate:(id)arg10 conditionCodings:(id)arg11 categoryCodings:(id)arg12 asserter:(id)arg13 abatement:(id)arg14 onset:(id)arg15 recordedDate:(id)arg16 clinicalStatusCoding:(id)arg17 verificationStatusCoding:(id)arg18 severityCodings:(id)arg19 bodySitesCodings:(id)arg20;
+ (id)defaultDisplayString;
+ (id)indexableConceptKeyPaths;
+ (id)severityCodingsPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;
+ (id)verificationStatusCodingPreferredSystems;

- (void).cxx_destruct;
- (void)_setAbatement:(id)arg1;
- (void)_setAsserter:(id)arg1;
- (void)_setBodySites:(id)arg1;
- (void)_setBodySitesCodings:(id)arg1;
- (void)_setCategory:(id)arg1;
- (void)_setCategoryCodings:(id)arg1;
- (void)_setClinicalStatus:(id)arg1;
- (void)_setClinicalStatusCoding:(id)arg1;
- (void)_setCondition:(id)arg1;
- (void)_setConditionCodings:(id)arg1;
- (void)_setOnset:(id)arg1;
- (void)_setRecordedDate:(id)arg1;
- (void)_setSeverity:(id)arg1;
- (void)_setSeverityCodings:(id)arg1;
- (void)_setVerificationStatus:(id)arg1;
- (void)_setVerificationStatusCoding:(id)arg1;
- (id)_validateConfigurationWithOptions:(unsigned long long)arg1;
- (id)abatement;
- (bool)applyConcepts:(id)arg1 forKeyPath:(id)arg2 error:(id*)arg3;
- (id)asserter;
- (id)bodySites;
- (id)bodySitesCodings;
- (id)bodySitesCodingsCollection;
- (id)bodySitesCodingsContexts;
- (id)bodySitesCodingsTasks;
- (id)category;
- (id)categoryCodings;
- (id)categoryCodingsCollection;
- (id)categoryCodingsContext;
- (id)categoryCodingsTasks;
- (id)clinicalStatus;
- (id)clinicalStatusCoding;
- (id)clinicalStatusCodingCollection;
- (id)clinicalStatusCodingContext;
- (id)clinicalStatusCodingTasks;
- (id)codingsForKeyPath:(id)arg1 error:(id*)arg2;
- (id)condition;
- (id)conditionCodings;
- (id)conditionCodingsCollection;
- (id)conditionCodingsContext;
- (id)conditionCodingsTasks;
- (id)conditionRecordType;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEquivalent:(id)arg1;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (id)onset;
- (id)recordedDate;
- (id)severity;
- (id)severityCodings;
- (id)severityCodingsCollection;
- (id)severityCodingsContext;
- (id)severityCodingsTasks;
- (id)verificationStatus;
- (id)verificationStatusCoding;
- (id)verificationStatusCodingCollection;
- (id)verificationStatusCodingContext;
- (id)verificationStatusCodingTasks;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;

// Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI

- (id)codings;
- (long long)recordCategoryType;
- (id)title;
- (id)titleDisplayStringForDetailViewController;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
