/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKConceptAttribute : NSObject <NSCopying, NSSecureCoding> {
    HKConcept * _concept;
    long long  _identifier;
    NSString * _name;
    <NSCopying><NSSecureCoding> * _value;
    long long  _valueType;
}

@property (nonatomic, readonly) HKConcept *concept;
@property (nonatomic, readonly) long long identifier;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly, copy) <NSCopying><NSSecureCoding> *value;
@property (nonatomic, readonly) long long valueType;

+ (id)_attributeWithIdentifier:(long long)arg1 name:(id)arg2 valueType:(long long)arg3 value:(id)arg4;
+ (id)_attributeWithName:(id)arg1 valueType:(long long)arg2;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_attributeBySettingConcept:(id)arg1;
- (id)_init;
- (id)_initWithIdentifier:(long long)arg1 name:(id)arg2 valueType:(long long)arg3 value:(id)arg4;
- (id)concept;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (long long)identifier;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)name;
- (id)value;
- (long long)valueType;

@end
