/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKDiagnosticTestResult : HKMedicalRecord <HDCoding, HKConceptIndexable, NSCopying, NSSecureCoding> {
    HKConcept * _bodySite;
    NSArray * _bodySiteCodings;
    NSString * _category;
    NSString * _comments;
    HKConcept * _diagnosticTest;
    NSArray * _diagnosticTestCodings;
    HKMedicalDate * _effectiveEndDate;
    HKMedicalDate * _effectiveStartDate;
    HKConcept * _interpretation;
    NSArray * _interpretationCodings;
    HKMedicalDate * _issueDate;
    HKConcept * _method;
    NSArray * _methodCodings;
    NSArray * _performers;
    NSArray * _referenceRanges;
    HKConcept * _status;
    HKMedicalCoding * _statusCoding;
    HKInspectableValueCollection * _value;
}

@property (readonly) NSUUID *UUID;
@property (readonly, copy) HKConcept *bodySite;
@property (readonly, copy) NSArray *bodySiteCodings;
@property (readonly, copy) NSString *category;
@property (readonly, copy) NSString *comments;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy) HKConcept *diagnosticTest;
@property (readonly, copy) NSArray *diagnosticTestCodings;
@property (readonly, copy) HKDiagnosticTestResultType *diagnosticTestResultType;
@property (readonly, copy) HKMedicalDate *effectiveEndDate;
@property (readonly, copy) HKMedicalDate *effectiveStartDate;
@property (readonly) unsigned long long hash;
@property (readonly, copy) HKConcept *interpretation;
@property (readonly, copy) NSArray *interpretationCodings;
@property (readonly, copy) HKMedicalDate *issueDate;
@property (nonatomic, readonly, copy) NSLocale *locale;
@property (readonly, copy) HKConcept *method;
@property (readonly, copy) NSArray *methodCodings;
@property (readonly, copy) NSArray *performers;
@property (readonly, copy) NSArray *referenceRanges;
@property (readonly, copy) HKConcept *status;
@property (readonly, copy) HKMedicalCoding *statusCoding;
@property (readonly) Class superclass;
@property (readonly, copy) HKInspectableValueCollection *value;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)_newDiagnosticTestResultWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 sortDate:(id)arg10 diagnosticTestCodings:(id)arg11 value:(id)arg12 referenceRanges:(id)arg13 effectiveStartDate:(id)arg14 category:(id)arg15 issueDate:(id)arg16 effectiveEndDate:(id)arg17 statusCoding:(id)arg18 interpretationCodings:(id)arg19 comments:(id)arg20 bodySiteCodings:(id)arg21 methodCodings:(id)arg22 performers:(id)arg23 config:(id /* block */)arg24;
+ (id)bodySiteCodingsPreferredSystems;
+ (id)cachedConceptRelationshipKeyPaths;
+ (id)defaultDisplayString;
+ (id)diagnosticTestCodingsPreferredSystems;
+ (id)diagnosticTestResultWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 diagnosticTestCodings:(id)arg10 value:(id)arg11 referenceRanges:(id)arg12 effectiveStartDate:(id)arg13 category:(id)arg14 issueDate:(id)arg15 effectiveEndDate:(id)arg16 statusCoding:(id)arg17 interpretationCodings:(id)arg18 comments:(id)arg19 bodySiteCodings:(id)arg20 methodCodings:(id)arg21 performers:(id)arg22;
+ (id)diagnosticTestResultWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 sortDate:(id)arg10 diagnosticTestCodings:(id)arg11 value:(id)arg12 referenceRanges:(id)arg13 effectiveStartDate:(id)arg14 category:(id)arg15 issueDate:(id)arg16 effectiveEndDate:(id)arg17 statusCoding:(id)arg18 interpretationCodings:(id)arg19 comments:(id)arg20 bodySiteCodings:(id)arg21 methodCodings:(id)arg22 performers:(id)arg23;
+ (id)indexableConceptKeyPaths;
+ (id)interpretationCodingsPreferredSystems;
+ (id)methodCodingsPreferredSystems;
+ (id)statusCodingPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)_setBodySite:(id)arg1;
- (void)_setBodySiteCodings:(id)arg1;
- (void)_setCategory:(id)arg1;
- (void)_setComments:(id)arg1;
- (void)_setDiagnosticTest:(id)arg1;
- (void)_setDiagnosticTestCodings:(id)arg1;
- (void)_setEffectiveEndDate:(id)arg1;
- (void)_setEffectiveStartDate:(id)arg1;
- (void)_setInterpretation:(id)arg1;
- (void)_setInterpretationCodings:(id)arg1;
- (void)_setIssueDate:(id)arg1;
- (void)_setMethod:(id)arg1;
- (void)_setMethodCodings:(id)arg1;
- (void)_setPerformers:(id)arg1;
- (void)_setReferenceRanges:(id)arg1;
- (void)_setStatus:(id)arg1;
- (void)_setStatusCoding:(id)arg1;
- (void)_setValue:(id)arg1;
- (id)_validateConfigurationWithOptions:(unsigned long long)arg1;
- (bool)applyConcepts:(id)arg1 forKeyPath:(id)arg2 error:(id*)arg3;
- (id)bodySite;
- (id)bodySiteCodings;
- (id)bodySiteCodingsCollection;
- (id)bodySiteCodingsContext;
- (id)bodySiteCodingsTasks;
- (id)category;
- (id)codingsForKeyPath:(id)arg1 error:(id*)arg2;
- (id)comments;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)diagnosticTest;
- (id)diagnosticTestCodings;
- (id)diagnosticTestCodingsCollection;
- (id)diagnosticTestCodingsContext;
- (id)diagnosticTestCodingsTasks;
- (id)diagnosticTestResultType;
- (id)effectiveEndDate;
- (id)effectiveStartDate;
- (void)encodeWithCoder:(id)arg1;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)interpretation;
- (id)interpretationCodings;
- (id)interpretationCodingsCollection;
- (id)interpretationCodingsContext;
- (id)interpretationCodingsTasks;
- (bool)isEquivalent:(id)arg1;
- (id)issueDate;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (id)method;
- (id)methodCodings;
- (id)methodCodingsCollection;
- (id)methodCodingsContext;
- (id)methodCodingsTasks;
- (id)performers;
- (id)referenceRanges;
- (id)status;
- (id)statusCoding;
- (id)statusCodingCollection;
- (id)statusCodingContext;
- (id)statusCodingTasks;
- (id)value;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;
+ (bool)supportsDistinctByKeyPath:(id)arg1;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;
- (id)uniqueIdentifierForDistinctByKeyPath:(id)arg1 error:(id*)arg2;

// Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI

- (void)_displayItemsForCodedValueCollection:(id)arg1 healthRecordsStore:(id)arg2 preferredStyle:(long long)arg3 completion:(id /* block */)arg4;
- (void)_displayItemsForValuePreferedStyle:(long long)arg1 healthRecordsStore:(id)arg2 completion:(id /* block */)arg3;
- (id)chartValue;
- (id)chartableCodedQuantitySet;
- (id)codings;
- (void)fetchConceptRoomItemsWithHealthRecordsStore:(id)arg1 conceptStore:(id)arg2 completion:(id /* block */)arg3;
- (void)fetchDetailItemsWithHealthRecordsStore:(id)arg1 conceptStore:(id)arg2 completion:(id /* block */)arg3;
- (void)fetchObservationDetailItemsWithHealthRecordsStore:(id)arg1 style:(long long)arg2 completion:(id /* block */)arg3;
- (long long)recordCategoryType;
- (id)title;
- (id)titleDisplayStringForDetailViewController;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
