/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKMedicalCodingContext : NSObject <NSCopying, NSSecureCoding> {
    HKMedicalCodingCollection * _collection;
    NSString * _keyPath;
    HKSampleType * _sampleType;
}

@property (nonatomic, readonly, copy) HKMedicalCodingCollection *collection;
@property (nonatomic, readonly, copy) NSString *keyPath;
@property (nonatomic, readonly, copy) HKSampleType *sampleType;

+ (id)contextWithCodings:(id)arg1 sampleType:(id)arg2 keyPath:(id)arg3;
+ (id)contextWithCollection:(id)arg1 sampleType:(id)arg2 keyPath:(id)arg3;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)collection;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithCollection:(id)arg1 sampleType:(id)arg2 keyPath:(id)arg3;
- (bool)isEqual:(id)arg1;
- (id)keyPath;
- (id)sampleType;

@end
