/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HealthKit.framework/HealthKit
 */

@interface HKVaccinationRecord : HKMedicalRecord <HDCoding, HKConceptIndexable, NSCopying, NSSecureCoding> {
    HKMedicalDate * _administrationDate;
    HKConcept * _bodySite;
    NSArray * _bodySiteCodings;
    NSString * _doseNumber;
    NSString * _doseQuantity;
    HKMedicalDate * _expirationDate;
    bool  _notGiven;
    bool  _patientReported;
    NSString * _performer;
    NSString * _reaction;
    NSArray * _reasons;
    NSArray * _reasonsCodings;
    NSArray * _reasonsNotGiven;
    NSArray * _reasonsNotGivenCodings;
    HKConcept * _route;
    NSArray * _routeCodings;
    HKConcept * _status;
    HKMedicalCoding * _statusCoding;
    HKConcept * _vaccination;
    NSArray * _vaccinationCodings;
}

@property (readonly) NSUUID *UUID;
@property (readonly, copy) HKMedicalDate *administrationDate;
@property (readonly, copy) HKConcept *bodySite;
@property (readonly, copy) NSArray *bodySiteCodings;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *doseNumber;
@property (readonly, copy) NSString *doseQuantity;
@property (readonly, copy) HKMedicalDate *expirationDate;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSLocale *locale;
@property (readonly) bool notGiven;
@property (readonly) bool patientReported;
@property (readonly, copy) NSString *performer;
@property (readonly, copy) NSString *reaction;
@property (readonly, copy) NSArray *reasons;
@property (readonly, copy) NSArray *reasonsCodings;
@property (readonly, copy) NSArray *reasonsNotGiven;
@property (readonly, copy) NSArray *reasonsNotGivenCodings;
@property (readonly, copy) HKConcept *route;
@property (readonly, copy) NSArray *routeCodings;
@property (readonly, copy) HKConcept *status;
@property (readonly, copy) HKMedicalCoding *statusCoding;
@property (readonly) Class superclass;
@property (readonly, copy) HKConcept *vaccination;
@property (readonly, copy) NSArray *vaccinationCodings;
@property (readonly, copy) HKVaccinationRecordType *vaccinationRecordType;

// Image: /System/Library/Frameworks/HealthKit.framework/HealthKit

+ (bool)_isConcreteObjectClass;
+ (id)_newVaccinationRecordWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 sortDate:(id)arg10 vaccinationCodings:(id)arg11 expirationDate:(id)arg12 doseNumber:(id)arg13 doseQuantity:(id)arg14 performer:(id)arg15 bodySiteCodings:(id)arg16 reaction:(id)arg17 notGiven:(bool)arg18 administrationDate:(id)arg19 statusCoding:(id)arg20 patientReported:(bool)arg21 routeCodings:(id)arg22 reasonsCodings:(id)arg23 reasonsNotGivenCodings:(id)arg24 config:(id /* block */)arg25;
+ (id)bodySiteCodingsPreferredSystems;
+ (id)cachedConceptRelationshipKeyPaths;
+ (id)defaultDisplayString;
+ (id)indexableConceptKeyPaths;
+ (id)reasonsCodingsPreferredSystems;
+ (id)reasonsNotGivenCodingsPreferredSystems;
+ (id)routeCodingsPreferredSystems;
+ (id)statusCodingPreferredSystems;
+ (bool)supportsEquivalence;
+ (bool)supportsSecureCoding;
+ (id)vaccinationCodingsPreferredSystems;
+ (id)vaccinationRecordWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 sortDate:(id)arg10 vaccinationCodings:(id)arg11 expirationDate:(id)arg12 doseNumber:(id)arg13 doseQuantity:(id)arg14 performer:(id)arg15 bodySiteCodings:(id)arg16 reaction:(id)arg17 notGiven:(bool)arg18 administrationDate:(id)arg19 statusCoding:(id)arg20 patientReported:(bool)arg21 routeCodings:(id)arg22 reasonsCodings:(id)arg23 reasonsNotGivenCodings:(id)arg24;
+ (id)vaccinationRecordWithType:(id)arg1 note:(id)arg2 enteredInError:(bool)arg3 modifiedDate:(id)arg4 FHIRIdentifier:(id)arg5 locale:(id)arg6 extractionVersion:(long long)arg7 device:(id)arg8 metadata:(id)arg9 vaccinationCodings:(id)arg10 expirationDate:(id)arg11 doseNumber:(id)arg12 doseQuantity:(id)arg13 performer:(id)arg14 bodySiteCodings:(id)arg15 reaction:(id)arg16 notGiven:(bool)arg17 administrationDate:(id)arg18 statusCoding:(id)arg19 patientReported:(bool)arg20 routeCodings:(id)arg21 reasonsCodings:(id)arg22 reasonsNotGivenCodings:(id)arg23;

- (void).cxx_destruct;
- (void)_setAdministrationDate:(id)arg1;
- (void)_setBodySite:(id)arg1;
- (void)_setBodySiteCodings:(id)arg1;
- (void)_setDoseNumber:(id)arg1;
- (void)_setDoseQuantity:(id)arg1;
- (void)_setExpirationDate:(id)arg1;
- (void)_setNotGiven:(bool)arg1;
- (void)_setPatientReported:(bool)arg1;
- (void)_setPerformer:(id)arg1;
- (void)_setReaction:(id)arg1;
- (void)_setReasons:(id)arg1;
- (void)_setReasonsCodings:(id)arg1;
- (void)_setReasonsNotGiven:(id)arg1;
- (void)_setReasonsNotGivenCodings:(id)arg1;
- (void)_setRoute:(id)arg1;
- (void)_setRouteCodings:(id)arg1;
- (void)_setStatus:(id)arg1;
- (void)_setStatusCoding:(id)arg1;
- (void)_setVaccination:(id)arg1;
- (void)_setVaccinationCodings:(id)arg1;
- (id)_validateConfigurationWithOptions:(unsigned long long)arg1;
- (id)administrationDate;
- (bool)applyConcepts:(id)arg1 forKeyPath:(id)arg2 error:(id*)arg3;
- (id)bodySite;
- (id)bodySiteCodings;
- (id)bodySiteCodingsCollection;
- (id)bodySiteCodingsContext;
- (id)bodySiteCodingsTasks;
- (id)codingsForKeyPath:(id)arg1 error:(id*)arg2;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)doseNumber;
- (id)doseQuantity;
- (void)encodeWithCoder:(id)arg1;
- (id)expirationDate;
- (id)indexKeywords;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (bool)isEquivalent:(id)arg1;
- (id)medicalRecordCodings;
- (id)medicalRecordPreferredSystems;
- (bool)notGiven;
- (bool)patientReported;
- (id)performer;
- (id)reaction;
- (id)reasons;
- (id)reasonsCodings;
- (id)reasonsCodingsCollection;
- (id)reasonsCodingsContexts;
- (id)reasonsCodingsTasks;
- (id)reasonsNotGiven;
- (id)reasonsNotGivenCodings;
- (id)reasonsNotGivenCodingsCollection;
- (id)reasonsNotGivenCodingsContexts;
- (id)reasonsNotGivenCodingsTasks;
- (id)route;
- (id)routeCodings;
- (id)routeCodingsCollection;
- (id)routeCodingsContext;
- (id)routeCodingsTasks;
- (id)status;
- (id)statusCoding;
- (id)statusCodingCollection;
- (id)statusCodingContext;
- (id)statusCodingTasks;
- (id)vaccination;
- (id)vaccinationCodings;
- (id)vaccinationCodingsCollection;
- (id)vaccinationCodingsContext;
- (id)vaccinationCodingsTasks;
- (id)vaccinationRecordType;

// Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon

+ (id)createWithCodable:(id)arg1;
+ (Class)hd_dataEntityClass;

- (bool)addCodableRepresentationToCollection:(id)arg1;
- (id)codableRepresentationForSync;

// Image: /System/Library/PrivateFrameworks/HealthRecordsUI.framework/HealthRecordsUI

- (id)codings;
- (id)meaningfulDateTitle;
- (long long)recordCategoryType;
- (id)title;
- (id)titleDisplayStringForDetailViewController;

// Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI

- (id)sortDateTitle;

@end
