/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreMIDI.framework/CoreMIDI
 */

@interface BLEXPCConfiguration : NSObject <BLEXPCInterface>

- (void)setConfiguration:(id)arg1 reply:(id /* block */)arg2;

@end
