/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface _TtCV10RealityKit23__RKEntityUUIDComponent12Registration : Swift._SwiftObject {
    void componentType;
    void introspectionStruct;
}

@end
