/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface _TtCC10RealityKit25__RKEntityTransformActionP33_9181554796D1CD5D5774FC6D7811A58523MotionStateEventContext : Swift._SwiftObject {
    void action;
    void goal;
}

@end
