/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface _TtCC10RealityKit13AudioResource10AudioError : Swift._SwiftObject {
    void message;
}

@end
