/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface _TtCC10RealityKit20__SceneResourceCache5Entry : Swift._SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  assetBundle;
}

@end
