/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__SceneImportOperation : Swift._SwiftObject {
    void coreOperation;
}

@end
