/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKEntityInteractionManager : Swift._SwiftObject {
    void __entityLookupTable;
    void __interactions;
    void __simulationSceneCoordinator;
    void areInteractionsEnabled;
    void automaticallyInvokesStartTrigger;
    void customTriggerFiredActions;
    void key;
    void sceneRef;
}

@end
