/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.NetPassthroughEncoder : Swift._SwiftObject {
    void m_encoder;
    void m_payload;
}

@end
