/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RealityFileURLResolver : Swift._SwiftObject {
    void $__lazy_storage_$_schemePrefix;
    void assetPathPrefix;
    void resolvedURLByAssetPathPrefix;
}

@end
