/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.RERenderFrameSettings : Swift._SwiftObject {
    void _renderFrameSettings;
}

@end
