/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKEntityLookupTable : Swift._SwiftObject {
    void uuidToEntity;
}

@end
