/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.MultipeerConnectivityService : Swift._SwiftObject {
    void coreInvalidPeerID;
    void coreMultipeerConnectivityService;
    void coreNetworkSystem;
    void coreServiceLocator;
    void session;
}

@end
