/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKSimulationSceneCoordinator : Swift._SwiftObject {
    void delegate;
    void simulationState;
}

@end
