/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKEntityAnimateAction : RealityKit.__RKEntityAction {
    void animationComponents;
    void animationSpeed;
    void clipDuration;
    void clipReversed;
    void clipStart;
    void duration;
    void loopBehavior;
    void loopCount;
}

- (id)copyWithZone:(void*)arg1;

@end
