/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKEntityInteraction : Swift._SwiftObject {
    void action;
    void alternateAction;
    void enabled;
    void trigger;
}

@end
