/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__SceneResourceCache : Swift._SwiftObject {
    void entriesByURL;
    void lockQueue;
}

@end
