/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.AnimationResource : Swift._SwiftObject {
    void coreAsset;
    void name;
}

@end
