/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.InteractionNotificationsManager : Swift._SwiftObject

- (void)notificationTriggerDidPostWithNotification:(id)arg1;

@end
