/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKActiveSceneManager : Swift._SwiftObject {
    void activeScene;
    void observers;
}

@end
