/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.NetPassthroughDecoder : Swift._SwiftObject {
    void m_decoder;
    void m_payload;
}

@end
