/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__AssetLoadRequest : Swift._SwiftObject {
    void coreAssetRequest;
}

@end
