/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.Entity : Swift._SwiftObject {
    void coreEntity;
    void swiftChildren;
}

@end
