/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__Engine : Swift._SwiftObject {
    void configuration;
    void coreEngine;
    void hasRenderedThisFrame;
    void isExternallyManaged;
    void queue;
    void services;
    void startCount;
}

@end
