/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.IntrospectionDataCleanupHelper : Swift._SwiftObject {
    void rawData;
}

@end
