/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.Scene : Swift._SwiftObject {
    void $__lazy_storage_$___interactionService;
    void $__lazy_storage_$_eventService;
    void __audioListener;
    void activeCamera;
    void coreScene;
    void defaultCamera;
    void entities;
    void internalAudioListener;
    void session;
    void synchronizationService;
}

@end
