/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.LoadManager : Swift._SwiftObject {
    void queue;
    void sceneResourceCache;
}

@end
