/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.PhysicsMaterialResource : Swift._SwiftObject {
    void coreAsset;
}

@end
