/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.RKARProbeRenderManager : Swift._SwiftObject {
    void addProbeQueue;
    void enableRendering;
    void engine;
    void fadeInProbes;
    void fadeOutProbes;
    void globalFadeState;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  globalProbe;
    void globalUpdateQueue;
    void locked;
    void probeEntities;
    void scene;
    void updateProbeQueue;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  updatingGlobalProbe;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  updatingProbe;
}

@end
