/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.RKARProbePlacementManager : Swift._SwiftObject {
    void globalProbeAnchor;
    void probeAABBs;
    void probeAnchors;
    void probeTick;
}

@end
