/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.SceneManager : Swift._SwiftObject {
    void coreECSManager;
    void customComponentTypesToHandles;
    void handlesToCustomComponentTypes;
    void scenes;
}

@end
