/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.ShapeResource : Swift._SwiftObject {
    void coreAsset;
    void pose;
}

@end
