/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.REEventBus : Swift._SwiftObject {
    void coreHandle;
    void dispatchersByHandle;
}

@end
