/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.RERenderFrameWorkload : Swift._SwiftObject {
    void _renderFrameWorkload;
}

@end
