/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.AnimationPlaybackController : Swift._SwiftObject {
    void entity;
    void identifier;
}

@end
