/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.EnvironmentResource : Swift._SwiftObject {
    void coreIBLAsset;
    void coreSkyboxAsset;
}

@end
