/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Combine.framework/Combine
 */

@interface Combine.ObservableObjectPublisher : Swift._SwiftObject {
    void connections;
    void identifier;
    void lock;
}

@end
