/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKClientToken : NSObject {
    long long  _connectionIdentifier;
    bool  _namedConnection;
    NSXPCConnection * _serverConnection;
    NSXPCListenerEndpoint * _serverEndpoint;
    NSNumber * _targetUID;
    NSXPCConnection * _tokenConnection;
    NSString * _tokenID;
}

@property (nonatomic, readonly) NSXPCListenerEndpoint *configurationEndpoint;
@property (nonatomic, readonly) NSXPCListenerEndpoint *endpoint;
@property (nonatomic, readonly) NSXPCConnection *serverConnection;
@property (nonatomic, readonly) NSXPCConnection *tokenConnection;
@property (nonatomic, readonly) NSString *tokenID;

- (void).cxx_destruct;
- (id)configurationEndpoint;
- (bool)connectWithError:(id*)arg1;
- (void)dealloc;
- (id)endpoint;
- (id)initWithTokenID:(id)arg1;
- (id)initWithTokenID:(id)arg1 serverEndpoint:(id)arg2 targetUID:(id)arg3;
- (id)serverConnection;
- (id)sessionWithLAContext:(id)arg1 error:(id*)arg2;
- (id)tokenConnection;
- (id)tokenID;
- (id)withError:(id*)arg1 invoke:(id /* block */)arg2;

@end
