/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKTokenDriverConfiguration : NSObject {
    NSString * _classID;
    TKTokenConfigurationProxy * _proxy;
}

@property (nonatomic, readonly) NSString *classID;
@property (nonatomic, readonly, copy) NSDictionary *tokenConfigurations;

+ (id)configurationServer;
+ (id)driverConfigurations;
+ (void)setConfigurationServer:(id)arg1;

- (void).cxx_destruct;
- (id)addTokenConfigurationForTokenInstanceID:(id)arg1;
- (id)beginTransaction;
- (id)classID;
- (id)createTokenConfigurationWithInstanceID:(id)arg1 persistent:(bool)arg2;
- (id)initWithClassID:(id)arg1 proxy:(id)arg2;
- (void)removeTokenConfigurationForTokenInstanceID:(id)arg1;
- (id)tokenConfigurations;

@end
