/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKTokenConfigurationTransaction : NSObject {
    TKTokenConfigurationProxy * _proxy;
}

- (void).cxx_destruct;
- (void)commit;
- (void)dealloc;
- (id)initWithProxy:(id)arg1;

@end
