/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CryptoTokenKit.framework/CryptoTokenKit
 */

@interface TKTokenConfigurationProxy : NSObject {
    <NSXPCProxyCreating> * _proxyCreator;
}

@property (nonatomic, readonly) <NSXPCProxyCreating> *proxyCreator;

- (void).cxx_destruct;
- (id)configurationProtocol;
- (id)initWithProxyCreator:(id)arg1;
- (id)proxyCreator;

@end
