/* Generated by RuntimeBrowser.
 */

@protocol _CDUserContext <_CDLocalContext>

@required

- (<_CDLocalContext> *)localContext;
- (struct NSDictionary { Class x1; }*)valuesForKeyPaths:(NSArray *)arg1;
- (NSArray *)valuesForKeyPaths:(NSArray *)arg1 inContextsMatchingPredicate:(_CDContextualPredicate *)arg2;

@end
