/* Generated by RuntimeBrowser.
 */

@protocol _GEOThrottler <NSObject>

@required

+ (bool)stateIsExpired:(struct NSDictionary { Class x1; }*)arg1;

- (bool)addRequestTimestamp;
- (struct NSDictionary { Class x1; }*)captureState;
- (id)initWithKeyPath:(NSString *)arg1 requestCount:(unsigned long long)arg2 interval:(double)arg3 savedState:(struct NSDictionary { Class x1; }*)arg4;
- (bool)isExpired;
- (NSString *)keyPath;
- (unsigned int)maxReqCount;
- (unsigned long long)remainingEntries;
- (double)timeUntilReset;
- (double)timeWindow;
- (NSDictionary *)userInfoForError;

@end
