/* Generated by RuntimeBrowser.
 */

@protocol _PARResult_Template <NSObject>

@required

- (NSData *)cardData;
- (NSString *)completion;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setCardData:(NSData *)arg1;
- (void)setCompletion:(NSString *)arg1;
- (void)setTitle:(NSString *)arg1;
- (NSString *)title;

@end
