/* Generated by RuntimeBrowser.
 */

@protocol _SFAdaptivePreviewViewControllerDelegate

@required

- (void)adaptivePreviewViewControlerWillDisableLinkPreview:(_SFAdaptivePreviewViewController *)arg1;
- (UIViewController *)adaptivePreviewViewController:(_SFAdaptivePreviewViewController *)arg1 requestLinkPreviewViewControllerWithURL:(NSURL *)arg2;

@end
