/* Generated by RuntimeBrowser.
 */

@protocol _SFBrowserDocument <NSObject>

@required

- (NSURL *)URLForPerSitePreferences;
- (bool)canHideToolbar;
- (void)perSiteSettingsUIPresentSettings;
- (<SFReaderContext> *)readerContext;
- (void)reloadEnablingContentBlockers:(bool)arg1;
- (_SFReloadOptionsController *)reloadOptionsController;
- (bool)wasLoadedWithContentBlockersEnabled;
- (_SFWebView *)webView;

@end
