/* Generated by RuntimeBrowser.
 */

@protocol _UISheetInteractionDelegate <NSObject>

@optional

- (struct CGPoint { double x1; double x2; })offsetForInterruptedAnimationInSheetInteraction:(_UISheetInteraction *)arg1;
- (void)sheetInteraction:(_UISheetInteraction *)arg1 didChangeOffset:(struct CGPoint { double x1; double x2; })arg2;
- (bool)sheetInteraction:(_UISheetInteraction *)arg1 shouldBeginHorizontalRubberBandingAtPoint:(struct CGPoint { double x1; double x2; })arg2;

@end
