/* Generated by RuntimeBrowser.
 */

@protocol _WKWebAuthenticationPanelDelegate <NSObject>

@optional

- (void)panel:(_WKWebAuthenticationPanel *)arg1 dismissWebAuthenticationPanelWithResult:(long long)arg2;
- (void)panel:(_WKWebAuthenticationPanel *)arg1 updateWebAuthenticationPanel:(long long)arg2;

@end
