/* Generated by RuntimeBrowser.
 */

@protocol ACDPluginEntryProtocol

@required

- (id)principalObject;
- (bool)principalObjectRespondsToSelector:(SEL)arg1;
- (NSSet *)supportedAccountTypes;
- (NSSet *)supportedDataclasses;

@end
