/* Generated by RuntimeBrowser.
 */

@protocol ACUISignInControllerDelegate

@optional

- (void)signInControllerDidCancel;
- (void)signInControllerDidCompleteWithSuccess:(bool)arg1 error:(NSError *)arg2;

@end
