/* Generated by RuntimeBrowser.
 */

@protocol AFClockTimerListening <NSObject>

@required

- (void)clockTimerObserver:(AFClockTimerObserver *)arg1 snapshotDidUpdateFrom:(AFClockTimerSnapshot *)arg2 to:(AFClockTimerSnapshot *)arg3;
- (void)clockTimerObserver:(AFClockTimerObserver *)arg1 timerDidDismiss:(NSUUID *)arg2;
- (void)clockTimerObserver:(AFClockTimerObserver *)arg1 timerDidFire:(NSUUID *)arg2;

@end
