/* Generated by RuntimeBrowser.
 */

@protocol AMSAuthKitUpdateController <NSObject>

@required

- (AMSLazyPromise *)performAuthKitUpdateForAccount:(ACAccount *)arg1 options:(AMSAuthenticateOptions *)arg2;

@end
