/* Generated by RuntimeBrowser.
 */

@protocol ARBoardControllerDelegate <NSObject>

@required

- (void)boardControlerDidSwitchToDeviceHeld:(ARBoardController *)arg1;
- (void)boardController:(ARBoardController *)arg1 didSwitchToDeviceWorn:(NSDictionary *)arg2;

@end
