/* Generated by RuntimeBrowser.
 */

@protocol ARPresentationInternalObserver <NSObject>

@optional

- (void)presentation:(ARPresentation *)arg1 didTransitionToMode:(long long)arg2;
- (void)presentation:(ARPresentation *)arg1 willTransitionToMode:(long long)arg2;

@end
