/* Generated by RuntimeBrowser.
 */

@protocol ARStarBoardSceneManagerObserver <NSObject>

@required

- (void)starBoardSceneConnected:(UIScene *)arg1;
- (void)starBoardSceneDisconnected:(UIScene *)arg1;

@end
