/* Generated by RuntimeBrowser.
 */

@protocol ARUIRingGroupControllerDelegate <NSObject>

@required

- (void)ringGroupControllerNeedsUpdate:(ARUIRingGroupController *)arg1;
- (void)ringGroupControllerWillAddCelebrationOfType:(unsigned long long)arg1;

@end
