/* Generated by RuntimeBrowser.
 */

@protocol AXPIFingerAppearanceDelegate <NSObject>

@required

- (UIColor *)circularProgressFillColor;
- (UIColor *)deselectedFillColor;
- (UIColor *)deselectedStrokeColor;
- (double)fingerDiameter;
- (double)fingerInnerCircleInnerRadius;
- (double)fingerInnerRadius;
- (double)fingerOuterRadius;
- (UIColor *)pressedCircularProgressFillColor;
- (UIColor *)selectedFillColor;
- (UIColor *)selectedStrokeColor;
- (UIColor *)strokeOutlineColor;
- (double)strokeOutlineWidth;
- (double)strokeWidth;

@end
