/* Generated by RuntimeBrowser.
 */

@protocol BCSActionPrivate <BCSAction>

@required

- (NSArray *)appLinks;
- (NSDictionary *)debugDescriptionDictionary;
- (NSString *)extraPreviewText;
- (bool)isInvalidDataAction;
- (bool)isWiFiAction;

@end
