/* Generated by RuntimeBrowser.
 */

@protocol BCSCloudServerRouteProvider <NSObject>

@required

- (NSString *)apiKey;
- (NSString *)container;
- (NSString *)environment;
- (NSURL *)urlForLookupActionAPI;
- (NSURL *)urlForQueryActionAPI;

@end
