/* Generated by RuntimeBrowser.
 */

@protocol BYEnvironmentDependencyReceiver <NSObject>

@optional

- (<BYDeviceProvider> *)deviceProvider;
- (void)setDeviceProvider:(id <BYDeviceProvider>)arg1;

@end
