/* Generated by RuntimeBrowser.
 */

@protocol CardDAVDelegateInfoProvider <NSObject>

@required

- (NSArray *)collectDelegatesForAccount:(ACAccount *)arg1;
- (NSArray *)collectExpiredDelgatesForAccount:(ACAccount *)arg1;

@end
