/* Generated by RuntimeBrowser.
 */

@protocol CFXAnimojiTrackingLossDelegate <NSObject>

@required

- (void)hideAnimojiFaceReticleForTrackingGain;
- (void)setupAnimojiFaceReticleForTrackingLoss;
- (bool)shouldShowAnimojiFaceReticle;
- (void)showAnimojiFaceReticleForTrackingLoss;

@end
