/* Generated by RuntimeBrowser.
 */

@protocol CKNicknameUpdatesCollectionViewCellDelegate <NSObject>

@required

- (void)updateCell:(CKNicknameUpdatesCollectionViewCell *)arg1 ignoreButtonTappedForBannerView:(CKNicknameBannerView *)arg2;
- (void)updateCell:(CKNicknameUpdatesCollectionViewCell *)arg1 updateButtonTappedForBannerView:(CKNicknameBannerView *)arg2;

@end
