/* Generated by RuntimeBrowser.
 */

@protocol CKNicknameBannerViewDelegate <NSObject>

@required

- (void)nicknameBannerViewActionButtonTapped:(CKNicknameBannerView *)arg1;
- (void)nicknameBannerViewDismissButtonTapped:(CKNicknameBannerView *)arg1;

@end
