/* Generated by RuntimeBrowser.
 */

@protocol CLSSimilarlyStackableItem <NSObject>

@required

- (NSData *)clsDistanceIdentity;
- (NSString *)clsIdentifier;
- (VNSceneprint *)clsSceneprint;
- (NSDate *)cls_universalDate;

@end
