/* Generated by RuntimeBrowser.
 */

@protocol CPAnalyticsDynamicPropertyProvider <NSObject>

@required

- (struct NSObject { Class x1; }*)getDynamicProperty:(NSString *)arg1 forEventName:(NSString *)arg2 withPayload:(NSDictionary *)arg3;

@end
