/* Generated by RuntimeBrowser.
 */

@protocol CRSUIInstrumentClusterSceneSettings <NSObject>

@required

- (unsigned long long)itemType;
- (unsigned long long)showsCompass;
- (unsigned long long)showsSpeedLimit;

@end
