/* Generated by RuntimeBrowser.
 */

@protocol CSAppearanceProviding <NSObject>

@required

- (NSString *)appearanceIdentifier;
- (UIColor *)backgroundColor;
- (long long)backgroundStyle;
- (NSSet *)components;
- (_UILegibilitySettings *)legibilitySettings;

@end
