/* Generated by RuntimeBrowser.
 */

@protocol CSPhraseSpotterEnabledMonitorDelegate <NSObject>

@required

- (void)CSPhraseSpotterEnabledMonitor:(CSPhraseSpotterEnabledMonitor *)arg1 didReceiveEnabled:(bool)arg2;

@end
