/* Generated by RuntimeBrowser.
 */

@protocol CSTodayOverlayProviding <NSObject>

@required

- (<SBFTodayOverlayControlling><CSExternalBehaviorProviding><CSExternalEventHandling> *)newTodayOverlayController;
- (bool)wantsTodayOverlay;

@end
