/* Generated by RuntimeBrowser.
 */

@protocol CSVoiceTriggerXPCServiceDelegate <NSObject>

@required

- (void)voiceTriggerXPCService:(CSVoiceTriggerXPCService *)arg1 setPhraseSpotterBypassing:(bool)arg2;

@end
