/* Generated by RuntimeBrowser.
 */

@protocol CTXPCServiceCellularUsagePolicyInterface

@required

- (void)saveDataMode:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: CTServiceDescriptor *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)setSaveDataMode:(void *)arg1 enable:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 8: CTServiceDescriptor *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
