/* Generated by RuntimeBrowser.
 */

@protocol EDDatabaseChangeHookResponder <NSObject>

@optional

- (void)persistenceIsInitializingDatabaseWithConnection:(EDPersistenceDatabaseConnection *)arg1;

@end
