/* Generated by RuntimeBrowser.
 */

@protocol EFSQLGeneratorPredicateNode <NSObject>

@required

- (<EFSQLExpressable> *)sqlExpressableWithTableExpressions:(NSMutableArray *)arg1;
- (void)traverseTreeWithAliasMap:(NSMutableDictionary *)arg1;

@end
