/* Generated by RuntimeBrowser.
 */

@protocol FCForYouBridgedFeedGroup

@required

- (NSArray *)assetHandles;
- (NSString *)backingTagID;
- (NSSet *)equivalentTopicIDs;
- (NSArray *)headlines;
- (NSString *)identifier;
- (NSArray *)webEmbedURLs;

@end
