/* Generated by RuntimeBrowser.
 */

@protocol GKMultiplayerPlayerCountViewControllerDelegate <NSObject>

@required

- (void)multiplayerPlayerCountViewController:(GKMultiplayerPlayerCountViewController *)arg1 didSelectValue:(long long)arg2;

@end
