/* Generated by RuntimeBrowser.
 */

@protocol GKPlayerAvatarViewDelegate <NSObject>

@optional

- (void)didSelectPlayerAvatarView:(GKDashboardPlayerPhotoView *)arg1;
- (void)didSetPlayerAvatarImage:(GKDashboardPlayerPhotoView *)arg1;

@end
