/* Generated by RuntimeBrowser.
 */

@protocol HBColorPickerDelegate <NSObject>

@optional

- (void)colorPicker:(HBColorPickerViewController *)arg1 didAcceptColor:(UIColor *)arg2;
- (void)colorPicker:(HBColorPickerViewController *)arg1 didSelectColor:(UIColor *)arg2;
- (void)colorPickerDidCancel:(HBColorPickerViewController *)arg1;

@end
