/* Generated by RuntimeBrowser.
 */

@protocol HKConceptStoreServerInterface <NSObject>

@required

- (void)remote_breakAssociationFromSample:(void *)arg1 toConcept:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: HKSample *, HKConcept *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)remote_cleanUpAfterUnitTestWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)remote_conceptByResolvingContext:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 7: HKMedicalCodingContext *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, HKConcept *, void*
- (void)remote_currentIndexingState:(void *)arg1; // needs 1 arg types, found 6: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, unsigned long long, void*
- (void)remote_displayNamesByResolvingContexts:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 7: NSArray *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, void*
- (void)remote_makeAssociationFromSample:(void *)arg1 toConcept:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: HKSample *, HKConcept *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)remote_ontologyVersionWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSNumber *, NSError *, void*
- (void)remote_queryConceptByID:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: NSNumber *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, HKConcept *, NSError *, void*
- (void)remote_queryConceptsAssociatedToUserRecordsWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)remote_queryConceptsByAttribute:(void *)arg1 withValue:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: long long, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)remote_queryConceptsByRelationship:(void *)arg1 fromNodeWithID:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSString *, HKConceptIdentifier *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)remote_queryConceptsByRelationship:(void *)arg1 toNodeWithID:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSString *, HKConceptIdentifier *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)remote_queryCountOfConceptsAssociatedToUserRecordsWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, long long, NSError *, void*
- (void)remote_queryNodeNameForAttributeWithKeyID:(void *)arg1 value:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSNumber *, NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSString *, NSError *, void*
- (void)remote_queryRelationshipsForNodeWithID:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: HKConceptIdentifier *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)remote_resetOntologyUsingAssetAtLocation:(void *)arg1 rememberLocation:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: NSURL *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)remote_startTaskServerIfNeeded;
- (void)remote_testTaskServerWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, bool, NSError *, void*
- (void)remote_unitTest_queryConceptByExactNameMatch:(void *)arg1 completion:(void *)arg2; // needs 2 arg types, found 8: NSString *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, HKConcept *, NSError *, void*

@end
