/* Generated by RuntimeBrowser.
 */

@protocol HKConceptIndexable <HKCodedObject>

@required

+ (NSArray *)cachedConceptRelationshipKeyPaths;
+ (NSArray *)indexableConceptKeyPaths;

- (NSUUID *)UUID;
- (NSLocale *)locale;

@end
