/* Generated by RuntimeBrowser.
 */

@protocol HKInteractiveChartCurrentValueViewDelegate <NSObject>

@required

- (void)currentValueViewDidTapOnDateSelector:(HKInteractiveChartCurrentValueView *)arg1;
- (void)currentValueViewDidTapOnInfoButton:(HKInteractiveChartCurrentValueView *)arg1;

@end
