/* Generated by RuntimeBrowser.
 */

@protocol HKSampleTypeDateRangeControllerObserver <NSObject>

@required

- (void)sampleTypeDateRangeController:(HKSampleTypeDateRangeController *)arg1 didUpdateDateRanges:(struct NSDictionary { Class x1; }*)arg2;

@end
