/* Generated by RuntimeBrowser.
 */

@protocol HMDCameraNotificationCharacteristicsAvailabilityListenerDelegate

@required

- (void)listener:(HMDCameraNotificationCharacteristicsAvailabilityListener *)arg1 didUpdateAvailableCharacteristics:(NSSet *)arg2;

@end
