/* Generated by RuntimeBrowser.
 */

@protocol HMDNetworkRouterFirewallRuleManagerBackingStoreMirror <NSObject>

@required

- (bool)addOverrides:(struct NSDictionary { Class x1; }*)arg1 replace:(bool)arg2 options:(HMBProcessingOptions *)arg3 error:(id*)arg4;
- (struct NSDictionary { Class x1; }*)fetchAllNetworkDeclarationDataWithOptions:(HMBProcessingOptions *)arg1 error:(id*)arg2;
- (struct NSDictionary { Class x1; }*)fetchAllOverridesWithOptions:(HMBProcessingOptions *)arg1 error:(id*)arg2;
- (void)fetchCloudChangesWithOptions:(void *)arg1 ignoreLastFetchedAccessories:(void *)arg2 xpcActivity:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 10: HMBProcessingOptions *, bool, NSObject<OS_xpc_object> *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSSet *, NSError *, void*
- (void)fetchCloudRecordIDsForZoneID:(void *)arg1 options:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 9: CKRecordZoneID *, HMBProcessingOptions *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSSet *, NSError *, void*
- (void)fetchCloudRecordsForZoneID:(void *)arg1 recordID:(void *)arg2 options:(void *)arg3 completion:(void *)arg4; // needs 4 arg types, found 10: CKRecordZoneID *, CKRecordID *, HMBProcessingOptions *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSSet *, NSError *, void*
- (struct NSDictionary { Class x1; }*)fetchNetworkDeclarationDataForRecordIDs:(NSSet *)arg1 options:(HMBProcessingOptions *)arg2 error:(id*)arg3;
- (struct NSDictionary { Class x1; }*)fetchNetworkDeclarationDataForZoneName:(NSString *)arg1 options:(HMBProcessingOptions *)arg2 error:(id*)arg3;
- (struct NSDictionary { Class x1; }*)fetchOverridesForRecordIDs:(NSSet *)arg1 options:(HMBProcessingOptions *)arg2 error:(id*)arg3;
- (struct NSDictionary { Class x1; }*)fetchOverridesForZoneName:(NSString *)arg1 options:(HMBProcessingOptions *)arg2 error:(id*)arg3;
- (bool)removeAllLocalRulesWithOptions:(HMBProcessingOptions *)arg1 error:(id*)arg2;
- (bool)removeAllOverridesWithOptions:(HMBProcessingOptions *)arg1 error:(id*)arg2;
- (bool)removeOverridesForRecordIDs:(NSSet *)arg1 options:(HMBProcessingOptions *)arg2 error:(id*)arg3;
- (bool)removeOverridesForZoneName:(NSString *)arg1 recordName:(NSString *)arg2 options:(HMBProcessingOptions *)arg3 error:(id*)arg4;
- (void)setWatchedRecordIDs:(NSSet *)arg1;
- (NAFuture *)shutdownFuture;
- (NAFuture *)startupFuture;
- (NSSet *)watchedRecordIDs;

@end
