/* Generated by RuntimeBrowser.
 */

@protocol HMDSettingGroupProtocol <HMDSettingBaseProtocol>

@required

- (NSArray *)groups;
- (id)init;
- (id)initWithCoder:(NSCoder *)arg1;
- (NSArray *)settings;

@end
