/* Generated by RuntimeBrowser.
 */

@protocol HMICameraVideoFrameAnalyzer <NSObject>

@required

+ (NSDictionary *)classHierarchyMap;

- (HMICameraVideoFrameResult *)analyze:(HMICameraVideoFrame *)arg1 targetEventTypes:(long long)arg2 error:(id*)arg3;
- (id)init;
- (id)initWithConfidenceThresholds:(struct NSDictionary { Class x1; }*)arg1 nmsThreshold:(double)arg2 error:(id*)arg3;
- (void)preAnalyze:(HMICameraVideoFrame *)arg1;

@end
