/* Generated by RuntimeBrowser.
 */

@protocol HMICameraVideoFrameSelectorDelegate <NSObject>

@optional

- (void)selector:(HMICameraVideoFrameSelector *)arg1 maySelectFrame:(HMICameraVideoFrame *)arg2;

@end
