/* Generated by RuntimeBrowser.
 */

@protocol HRConceptViewControllerFactory

@required

- (UIViewController *)makeViewControllerForConcept:(HKConcept *)arg1 highlightedRecordId:(NSUUID *)arg2;
- (UIViewController *)makeViewControllerForConcept:(HKConcept *)arg1 highlightedRecordId:(NSUUID *)arg2;

@end
