/* Generated by RuntimeBrowser.
 */

@protocol HRElectrocardiogramReportDataSource <NSObject>

@required

- (NSDateComponents *)dateOfBirthComponents;
- (NSString *)firstName;
- (NSString *)lastName;
- (HKElectrocardiogram *)sample;
- (UIColor *)tintColor;

@end
