/* Generated by RuntimeBrowser.
 */

@protocol HROnboardingManagerDelegate <NSObject>

@optional

- (void)didCompleteOnboarding;
- (void)didDismissOnboarding;
- (void)didEnableAtrialFibrillationNotifications;
- (void)didTapOnAtrialFibrillationNotificationLearnMore;
- (void)didTapOnElectrocardiogram:(HKElectrocardiogram *)arg1;

@end
