/* Generated by RuntimeBrowser.
 */

@protocol HRRecordViewControllerFactory

@required

- (UIViewController *)makeDetailViewControllerForRecord:(HKMedicalRecord *)arg1;
- (UIViewController *)makeDetailViewControllerForRecord:(HKMedicalRecord *)arg1;
- (UIViewController *)makeViewControllerForRecord:(HKMedicalRecord *)arg1;
- (UIViewController *)makeViewControllerForRecord:(HKMedicalRecord *)arg1;

@end
