/* Generated by RuntimeBrowser.
 */

@protocol HUMediaSystemEditorGridViewControllerDelegate

@required

- (NAFuture *)mediaSystemEditorGrid:(HUMediaSystemEditorGridViewController *)arg1 didUpdateMediaSystemBuilder:(HFMediaSystemBuilder *)arg2;

@end
