/* Generated by RuntimeBrowser.
 */

@protocol HUTriggerSummaryActionGridViewControllerDelegate <NSObject, HUServiceGridViewControllerDelegate>

@required

- (void)triggerSummaryActionGridViewController:(HUTriggerSummaryActionGridViewController *)arg1 didUpdateTriggerBuilder:(HFTriggerBuilder *)arg2;

@end
