/* Generated by RuntimeBrowser.
 */

@protocol HUWallpaperPickerViewControllerDelegate <NSObject>

@required

- (void)wallpaperPickerDidCancel:(HUWallpaperPickerViewController *)arg1;
- (void)wallpaperPickerDidFinish:(HUWallpaperPickerViewController *)arg1 wallpaper:(HFWallpaper *)arg2 image:(UIImage *)arg3;

@end
