/* Generated by RuntimeBrowser.
 */

@protocol ICCloudServerListenerEndpointProvider <NSObject>

@required

- (NSXPCListenerEndpoint *)listenerEndpointForService:(long long)arg1 error:(id*)arg2;

@end
