/* Generated by RuntimeBrowser.
 */

@protocol INCodableCoding <NSObject>

@required

- (NSString *)cacheGroup;
- (NSString *)dictionaryKeyForKeyPath:(NSString *)arg1;
- (NSDictionary *)dictionaryRepresentation;
- (NSDictionary *)dictionaryRepresentationForLanguage:(NSString *)arg1;
- (NSString *)keyPrefix;
- (void)updateWithDictionary:(NSDictionary *)arg1;

@end
