/* Generated by RuntimeBrowser.
 */

@protocol INRunWorkflowIntentExport <NSObject, JSExport>

@required

- (id)init;
- (void)setStepIntentResponse:(INArchivedObject *)arg1;
- (void)setWorkflow:(INSpeakableString *)arg1;
- (INArchivedObject *)stepIntentResponse;
- (INSpeakableString *)workflow;

@end
