/* Generated by RuntimeBrowser.
 */

@protocol KNAnimationMovieHost <NSObject>

@required

- (void)applyMovieControl:(long long)arg1;
- (TSDMovieInfo *)movieInfo;
- (NSObject<TSKMediaPlayerController> *)playerController;

@end
