/* Generated by RuntimeBrowser.
 */

@protocol MapsSuggestionsPreloadableSource <MapsSuggestionsSource>

@required

- (bool)suggestionsEntriesAtLocation:(void *)arg1 period:(void *)arg2 handler:(void *)arg3; // needs 3 arg types, found 9: CLLocation *, struct NSDateInterval { Class x1; }*, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, struct NSArray { Class x1; }*, NSError *, void*

@end
