/* Generated by RuntimeBrowser.
 */

@protocol MapsSuggestionsShortcutSuggestor <NSObject>

@required

- (bool)suggestShortcutsOfType:(void *)arg1 handler:(void *)arg2; // needs 2 arg types, found 8: long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, struct NSArray { Class x1; }*, NSError *, void*

@end
