/* Generated by RuntimeBrowser.
 */

@protocol MFPhotoPickerControllerDelegate <NSObject>

@optional

- (void)photoPicker:(MFPhotoPickerController *)arg1 didDeselectAssetWithIdentifier:(NSString *)arg2;
- (void)photoPicker:(MFPhotoPickerController *)arg1 didSelectAssetWithIdentifier:(NSString *)arg2 mediaInfo:(NSDictionary *)arg3;
- (void)photoPickerDidCancel:(MFPhotoPickerController *)arg1;

@end
