/* Generated by RuntimeBrowser.
 */

@protocol MOVStreamPostProcessor <NSObject>

@required

- (struct __CVBuffer { }*)processedPixelBufferFrom:(struct __CVBuffer { }*)arg1 metadata:(NSDictionary *)arg2 reader:(MOVStreamReader *)arg3 error:(id*)arg4;

@end
