/* Generated by RuntimeBrowser.
 */

@protocol MPClientMediaPickerController <NSObject>

@required

- (void)remoteMediaPickerDidCancel;
- (void)remoteMediaPickerDidPickMediaItems:(MPMediaItemCollection *)arg1;

@end
