/* Generated by RuntimeBrowser.
 */

@protocol MPMiddlewareAutomaticDependencyOperation <MPMiddlewareOperation>

@required

- (struct NSMapTable { Class x1; }*)inputOperations;
- (NSArray *)inputProtocols;
- (NSArray *)outputProtocols;
- (void)setInputOperations:(struct NSMapTable { Class x1; }*)arg1;

@end
