/* Generated by RuntimeBrowser.
 */

@protocol MTBedtimeSessionTrackerDelegate <NSObject>

@required

- (void)bedtimeSessionTracker:(id <MTBedtimeSessionTracker>)arg1 sessionDidComplete:(id <MTBedtimeSession>)arg2;

@end
