/* Generated by RuntimeBrowser.
 */

@protocol MTMediaPlaylistItem <NSObject>

@optional

- (NSArray *)eventData;
- (unsigned long long)overallPosition;
- (unsigned long long)startOverallPosition;
- (long long)startPosition;

@end
