/* Generated by RuntimeBrowser.
 */

@protocol NAInterstitialAdvertisementHistoryRecorder

@required

- (long long)numberOfArticlesViewedSinceLastInterstitialAd;
- (void)recordArticleView;
- (void)recordInterstitialAdView;

@end
