/* Generated by RuntimeBrowser.
 */

@protocol NPKPaymentProvisioningFlowControllerDelegate <NSObject>

@required

- (void)paymentProvisioningFlowController:(NPKPaymentProvisioningFlowController *)arg1 didEncounterError:(NSError *)arg2 requestContext:(NPKPaymentProvisioningFlowControllerRequestContext *)arg3;
- (void)paymentProvisioningFlowController:(NPKPaymentProvisioningFlowController *)arg1 didTransitionFromStep:(int)arg2 toStep:(int)arg3 withContext:(NPKPaymentProvisioningFlowStepContext *)arg4;

@end
