/* Generated by RuntimeBrowser.
 */

@protocol NTKCircularAnalogDialColorPalette <NSObject>

@required

- (UIColor *)circularDialFillColor;
- (UIColor *)circularDialSubtickColor;
- (UIColor *)circularDialTickColor;

@end
