/* Generated by RuntimeBrowser.
 */

@protocol NTKVictoryAnalogBackgroundColorPalette <NSObject>

@required

- (UIColor *)analogDotColor;
- (UIColor *)backgroundColor;
- (bool)hasWhiteElements;
- (UIColor *)logoColor;
- (UIColor *)numbersColor;

@end
