/* Generated by RuntimeBrowser.
 */

@protocol PGQuestionFactory <NSObject>

@required

- (NSArray *)generateQuestionsWithPersons:(PHFetchResult *)arg1;
- (id)initWithManager:(PGManager *)arg1;

@end
