/* Generated by RuntimeBrowser.
 */

@protocol PGQuestion <NSObject>

@required

+ (id)questionForPerson:(PHPerson *)arg1;

- (bool)isEqualToQuestion:(id <PGQuestion>)arg1;
- (void)persist;
- (PHPerson *)person;
- (void)remove;
- (double)score;
- (long long)type;

@end
