/* Generated by RuntimeBrowser.
 */

@protocol PHPerformChangesRequestService <NSObject>

@required

- (NSPersistentStoreCoordinator *)persistentStoreCoordinator;
- (NSString *)uuidForSaveToken:(NSString *)arg1;

@end
