/* Generated by RuntimeBrowser.
 */

@protocol PHResourceRepairRequestDelegate <NSObject>

@required

- (void)resourceRepairRequest:(PHResourceRepairRequest *)arg1 didFinishWithSuccess:(bool)arg2;

@end
