/* Generated by RuntimeBrowser.
 */

@protocol PKPaletteShapesViewControllerDelegate <NSObject>

@required

- (void)shapesViewController:(PKPaletteShapesViewController *)arg1 didSelectShapeWithType:(long long)arg2;

@end
