/* Generated by RuntimeBrowser.
 */

@protocol PKPaletteMoreOptionsViewControllerDelegate <NSObject>

@required

- (void)moreOptionsViewControllerDidToggleAutoHide:(PKPaletteMoreOptionsViewController *)arg1;

@end
