/* Generated by RuntimeBrowser.
 */

@protocol PLAssetsdLibraryManagementServiceProtocol <NSObject>

@required

- (void)getActivePhotoLibrariesWithReply:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSSet *, NSError *, void*
- (void)getPhotoLibraryURLsWithReply:(void *)arg1; // needs 1 arg types, found 8: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSURL *, NSURL *, NSError *, void*
- (void)setSystemPhotoLibraryURL:(void *)arg1 bookmark:(void *)arg2 options:(void *)arg3 reply:(void *)arg4; // needs 4 arg types, found 9: NSURL *, NSData *, unsigned short, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
