/* Generated by RuntimeBrowser.
 */

@protocol PLClientAuthorization <NSObject>

@required

- (struct { unsigned int x1[8]; })clientAuditToken;
- (int)clientProcessIdentifier;
- (bool)directDatabaseWriteAuthorized;
- (bool)photoKitEntitled;
- (bool)photoKitEntitledFor:(NSString *)arg1;
- (NSString *)trustedCallerBundleID;
- (NSString *)trustedCallerDisplayName;

@end
