/* Generated by RuntimeBrowser.
 */

@protocol PMDebugCollectionViewControllerProtocol <NSObject>

@required

- (MiroAutoEditController *)autoEditController;
- (MiroMemory *)memory;
- (Project *)project;

@end
