/* Generated by RuntimeBrowser.
 */

@protocol PREResponsesTrialProtocol

@required

- (NSString *)experimentId;
- (NSString *)inferenceModelConfigPath;
- (NSString *)inferenceModelFilePath;
- (NSString *)inferenceModelName;
- (NSString *)treatmentId;

@end
