/* Generated by RuntimeBrowser.
 */

@protocol PUTabbedLibraryViewControllerContainerDelegate <NSObject>

@required

- (void)tabbedLibraryViewControllerDidChangeSelectedViewController:(PUTabbedLibraryViewController *)arg1;
- (void)tabbedLibraryViewControllerDidChangeViewControllers:(PUTabbedLibraryViewController *)arg1;

@end
