/* Generated by RuntimeBrowser.
 */

@protocol PXCMMWorkflowPresenting <NSObject>

@required

- (void)cancelWorkflow;
- (struct NSObject { Class x1; }*)workflowViewControllerWithContext:(PXCMMContext *)arg1;

@end
