/* Generated by RuntimeBrowser.
 */

@protocol PXCuratedLibraryFooterViewModelPresentationDelegate

@required

- (struct NSObject { Class x1; }*)presentingViewControllerForFooterViewModel:(PXCuratedLibraryFooterViewModel *)arg1;

@end
