/* Generated by RuntimeBrowser.
 */

@protocol PXCuratedLibraryEventLogger <NSObject>

@required

- (void)logAnalysisProgress:(float)arg1;
- (void)logLibraryItemsCount:(long long)arg1;
- (void)logViewControllerDidDisappear:(struct NSObject { Class x1; }*)arg1;
- (void)logViewControllerWillAppear:(struct NSObject { Class x1; }*)arg1;

@end
