/* Generated by RuntimeBrowser.
 */

@protocol PXCuratedLibraryFooterControllerDelegate <NSObject>

@required

- (void)footerControllerRevealFooter:(PXCuratedLibraryFooterController *)arg1;
- (struct NSObject { Class x1; }*)presentingViewControllerForFooterController:(PXCuratedLibraryFooterController *)arg1;

@end
