/* Generated by RuntimeBrowser.
 */

@protocol PXGSolidColorSource <PXGLayoutContentSource>

@required

- (struct UIColor { Class x1; }*)colorAtIndex:(unsigned int)arg1 inLayout:(PXGLayout *)arg2;

@end
