/* Generated by RuntimeBrowser.
 */

@protocol PXLibrarySummaryDataSource <NSObject>

@optional

- (<PXDisplayAssetCollection> *)topmostAssetCollection;
- (<PXBrowserVisibleContentSnapshot> *)visibleContentSnapshot;

@end
