/* Generated by RuntimeBrowser.
 */

@protocol PXNavigableForYouViewController

@required

- (UIViewController *)navigateToDetailsForMemoryWithLocalIdentifier:(NSString *)arg1;
- (PXMemoriesFeedUIViewController *)navigateToShowAllMemoriesFeedAnimated:(bool)arg1;

@end
