/* Generated by RuntimeBrowser.
 */

@protocol PXPhotosDataSourceProvider <NSObject>

@required

- (PXPhotosDataSource *)dataSourceManagerCreateInitialPhotosDataSource:(PXPhotoKitAssetsDataSourceManager *)arg1;

@end
