/* Generated by RuntimeBrowser.
 */

@protocol REMConflictResolving

@required

- (NSSet *)changedKeys;
- (NSString *)resolutionTokenKeyForChangedKey:(NSString *)arg1;
- (REMResolutionTokenMap *)resolutionTokenMap;
- (void)setResolutionTokenMap:(REMResolutionTokenMap *)arg1;

@end
