/* Generated by RuntimeBrowser.
 */

@protocol RMAssetResolver

@required

- (NSURLSessionDataTask *)dataTaskWithAsset:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: RMAsset *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSData *, NSError *, void*
- (NSURLSessionDownloadTask *)downloadTaskWithAsset:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 8: RMAsset *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSURL *, NSError *, void*

@end
