/* Generated by RuntimeBrowser.
 */

@protocol RMExtensionStatusPublisherRequestHandling <NSObject>

@required

- (void)queryStatusesOfTypes:(void *)arg1 onBehalfOfAccount:(void *)arg2 completionHandler:(void *)arg3; // needs 3 arg types, found 9: NSArray *, RMConfigurationAccount *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSDictionary *, NSError *, void*

@end
