/* Generated by RuntimeBrowser.
 */

@protocol RMUnresolvedAsset

@required

- (NSString *)identifier;
- (void)resolveWithAssetResolver:(void *)arg1 completionHandler:(void *)arg2; // needs 2 arg types, found 7: <RMAssetResolver> *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, RMResolvedAsset *, void*

@end
