/* Generated by RuntimeBrowser.
 */

@protocol SBAppStatusBarAssertionManagerObserver <NSObject>

@optional

- (void)statusBarAssertionManager:(SBAppStatusBarAssertionManager *)arg1 statusBarSettingsDidChange:(SBAppStatusBarSettings *)arg2;

@end
