/* Generated by RuntimeBrowser.
 */

@protocol SBApplicationSceneHandleProviding <SBApplicationSceneIdentityProviding>

@required

- (SBApplicationSceneHandle *)fetchOrCreateApplicationSceneHandleForApplication:(SBApplication *)arg1 withIdentity:(FBSSceneIdentity *)arg2;

@end
