/* Generated by RuntimeBrowser.
 */

@protocol SBApplicationHosting <NSObject>

@required

- (bool)canHostAnApp;
- (SBDeviceApplicationSceneHandle *)hostedAppSceneHandle;
- (NSArray *)hostedAppSceneHandles;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (bool)isHostingAnApp;

@end
