/* Generated by RuntimeBrowser.
 */

@protocol SBBarSwipeScreenEdgePanGestureRecognizerDelegate <NSObject>

@required

- (long long)touchGestureInterfaceOrientationForBarSwipeRecognizer:(SBBarSwipeScreenEdgePanGestureRecognizer *)arg1;

@end
