/* Generated by RuntimeBrowser.
 */

@protocol SBBarSwipeAffordanceDelegate <NSObject>

@required

- (BSAnimationSettings *)hideAnimationSettingsForBarSwipeAffordanceView:(SBBarSwipeAffordanceView *)arg1;
- (BSAnimationSettings *)unhideAnimationSettingsForBarSwipeAffordanceView:(SBBarSwipeAffordanceView *)arg1;

@end
