/* Generated by RuntimeBrowser.
 */

@protocol SBBannerContainerViewControllerDelegate

@required

- (void)bannerViewControllerDidDismissAction:(SBBannerContainerViewController *)arg1;
- (void)bannerViewControllerDidSelectAction:(SBBannerContainerViewController *)arg1;

@end
