/* Generated by RuntimeBrowser.
 */

@protocol SBFTodayOverlayObserving

@required

- (void)todayOverlayController:(id <SBFTodayOverlayControlling>)arg1 didChangePresentationProgress:(double)arg2;

@end
