/* Generated by RuntimeBrowser.
 */

@protocol SBGridSwitcherScrollProviding <SBFluidSwitcherScrollProviding>

@required

- (double)effectiveHorizontalSpacing;
- (unsigned long long)numberOfRows;

@end
