/* Generated by RuntimeBrowser.
 */

@protocol SBModalUIFluidDismissPanGestureRecognizerDelegate <SBSystemGestureRecognizerDelegate>

@required

- (long long)touchInterfaceOrientationForRecognizer:(SBModalUIFluidDismissPanGestureRecognizer *)arg1;

@end
