/* Generated by RuntimeBrowser.
 */

@protocol SBStarkBannerTargetObserver <NSObject>

@required

- (void)starkBannerTarget:(SBStarkBannerTarget *)arg1 didChangeContextWithDismissReason:(int)arg2;

@end
