/* Generated by RuntimeBrowser.
 */

@protocol SBStarkNotificationBannerItemDelegate <NSObject>

@required

- (void)executeAction:(NCNotificationAction *)arg1 forNotificationRequest:(NCNotificationRequest *)arg2;

@end
