/* Generated by RuntimeBrowser.
 */

@protocol SBStarkNotificationsConfiguring <NSObject>

@required

- (FBSDisplayIdentity *)displayIdentity;
- (UIWindow *)focusWindow;
- (bool)isConnectedWirelessly;
- (BSServiceConnectionEndpoint *)openServiceEndpoint;
- (CRCarPlayAppPolicy *)policyForApp:(SBApplication *)arg1;

@end
