/* Generated by RuntimeBrowser.
 */

@protocol SBTodayOverlayViewControllerDelegate

@required

- (void)todayOverlayViewControllerDidChangeHeaderVisibility:(SBTodayOverlayViewController *)arg1;

@end
