/* Generated by RuntimeBrowser.
 */

@protocol SBWorkspaceApplicationSceneTransitionContextDelegate <NSObject>

@required

- (SBLayoutState *)layoutStateForApplicationTransitionContext:(SBWorkspaceApplicationSceneTransitionContext *)arg1;
- (SBLayoutState *)previousLayoutStateForApplicationTransitionContext:(SBWorkspaceApplicationSceneTransitionContext *)arg1;

@end
