/* Generated by RuntimeBrowser.
 */

@protocol SearchUICardViewDelegate <NSObject>

@optional

- (UIViewController *)customViewControllerForCardSection:(SFCardSection *)arg1;
- (void)presentViewController:(UIViewController *)arg1;

@end
