/* Generated by RuntimeBrowser.
 */

@protocol SearchUIHomeScreenEngagementDelegate <NSObject>

@required

- (void)didEngageResult:(SFSearchResult *)arg1;
- (void)dismissIfNecessaryForIconDrag;

@end
