/* Generated by RuntimeBrowser.
 */

@protocol SEEndPointCertificateAuthority

@required

+ (id)endPointCertificateAuthorityWithIdentifier:(NSString *)arg1 subjectIdentifer:(NSString *)arg2 secureElementAttestation:(NSData *)arg3 error:(id*)arg4;

@end
