/* Generated by RuntimeBrowser.
 */

@protocol SEEndPoint

@required

+ (id)endPointWithIdentifier:(NSString *)arg1 certificateData:(NSData *)arg2 error:(id*)arg3;

- (void)addCertificateChain:(NSArray *)arg1;
- (NSError *)configurePrivateData:(NSData *)arg1 confidentialData:(NSData *)arg2 contaclessPersistentVisibility:(NSNumber *)arg3 wiredPersistentVisibility:(NSNumber *)arg4;
- (void)configurePrivateDataOffset:(unsigned short)arg1 privateDataLength:(unsigned short)arg2 confidentialDataOffset:(unsigned short)arg3 confidentialDataLength:(unsigned short)arg4 contaclessVisibility:(bool)arg5 wiredVisibility:(bool)arg6 contactlessLocalValidation:(bool)arg7 wiredLocalValidation:(bool)arg8;

@end
