/* Generated by RuntimeBrowser.
 */

@protocol SFPasswordDetailViewControllerDelegate <NSObject>

@optional

- (void)passwordDetailViewControllerDidUpdate:(SFPasswordDetailViewController *)arg1;

@end
