/* Generated by RuntimeBrowser.
 */

@protocol SiriButtonSource <SiriActivationSourceContext>

@required

- (void)didRecognizeButtonSinglePressUp;
- (<SiriAssertion> *)prepareForActivation;
- (<SiriAssertion> *)speechInteractionActivityWithTimestamp:(double)arg1;

@end
