/* Generated by RuntimeBrowser.
 */

@protocol SnowBoardImageCropperDelegate <NSObject>

@required

- (void)imageCropper:(SnowBoardImageCropper *)arg1 didFinishCroppingWithImage:(UIImage *)arg2 andRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3;
- (void)imageCropperDidCancel:(SnowBoardImageCropper *)arg1;

@end
