/* Generated by RuntimeBrowser.
 */

@protocol SRSensorKitServiceClientAuthorizationListening

@required

- (void)authorizedServicesDidChange:(NSSet *)arg1 forBundleIdentifier:(NSString *)arg2;

@end
