/* Generated by RuntimeBrowser.
 */

@protocol SRSPresentationAssertionServiceClientToServiceInterface <NSObject>

@required

- (oneway void)activate:(NSNumber *)arg1;
- (void)overrideState:(NSNumber *)arg1 config:(SRHMEConfig *)arg2;

@end
