/* Generated by RuntimeBrowser.
 */

@protocol SRSSessionControllerDelegate <NSObject>

@optional

- (void)sessionControllerActivated:(SRSSessionController *)arg1;
- (void)sessionControllerDidExitSTARMode:(SRSSessionController *)arg1;
- (void)sessionControllerInvalidated:(SRSSessionController *)arg1;
- (void)sessionControllerWillEnterSTARMode:(SRSSessionController *)arg1;

@end
