/* Generated by RuntimeBrowser.
 */

@protocol SRSSessionClientToServiceInterface <NSObject>

@required

- (oneway void)currentHMEStateWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSNumber *, NSError *, void*

@end
