/* Generated by RuntimeBrowser.
 */

@protocol SRSToolServiceClientToServiceInterface <NSObject>

@required

- (oneway void)bundleIdentifiersForStereoAREnabledAppsWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (oneway void)currentHMEConfigWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, SRHMEConfig *, NSError *, void*
- (oneway void)currentHMEStateWithCompletion:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSNumber *, NSError *, void*
- (oneway void)currentSTARProcesses:(void *)arg1; // needs 1 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSArray *, NSError *, void*
- (void)setCurrentHMEConfig:(SRHMEConfig *)arg1;
- (void)setCurrentHMEState:(NSNumber *)arg1;

@end
