/* Generated by RuntimeBrowser.
 */

@protocol STPINRemoteViewController <NSObject>

@required

- (void)pinServiceDidCompleteWithError:(void *)arg1 reply:(void *)arg2; // needs 2 arg types, found 7: NSError *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSError *, void*

@end
