/* Generated by RuntimeBrowser.
 */

@protocol SXConditionalHints <NSObject>

@required

- (bool)autoplacement;
- (bool)componentLayouts;
- (bool)componentStyles;
- (bool)componentTextStyles;
- (bool)components;
- (bool)documentStyle;
- (bool)textStyles;

@end
