/* Generated by RuntimeBrowser.
 */

@protocol TPPolicy <NSObject>

@required

- (NSString *)categoryForModel:(NSString *)arg1;
- (NSSet *)excludedViewsForModel:(NSString *)arg1;
- (NSString *)mapKeyToView:(NSDictionary *)arg1;
- (bool)peerInCategory:(NSString *)arg1 canAccessView:(NSString *)arg2;
- (bool)trustedPeerInCategory:(NSString *)arg1 canIntroduceCategory:(NSString *)arg2;
- (bool)unknownRedactions;
- (unsigned long long)version;
- (NSSet *)viewsForModel:(NSString *)arg1;

@end
