/* Generated by RuntimeBrowser.
 */

@protocol TPSCallWaitingControllerDelegate <NSObject>

@required

- (void)callWaitingController:(TPSCallWaitingController *)arg1 didChangeState:(long long)arg2 error:(NSError *)arg3;

@end
