/* Generated by RuntimeBrowser.
 */

@protocol TPSDuetContextualPredicateProtocol <NSObject>

@required

+ (_CDContextualPredicate *)contextualPredicateForDeliveryDuetEvent:(TPSDeliveryDuetEvent *)arg1;

@end
