/* Generated by RuntimeBrowser.
 */

@protocol TPSDiscoverabilityContentControllerDelegate <NSObject>

@required

- (void)discoverabilityContentController:(TPSDiscoverabilityContentController *)arg1 deliveryInfoFetchDidComplete:(NSDictionary *)arg2 error:(NSError *)arg3;

@end
