/* Generated by RuntimeBrowser.
 */

@protocol TRIControlCommand <NSObject, NSSecureCoding>

@required

- (<NSObject><NSSecureCoding> *)result;
- (bool)run;
- (void)setResult:(id <NSObject><NSSecureCoding>)arg1;

@end
