/* Generated by RuntimeBrowser.
 */

@protocol TRINamespaceFactorProviding <NSObject>

@required

- (TRILevel *)levelForFactor:(struct NSString { Class x1; }*)arg1;
- (unsigned int)namespaceCompatibilityVersion;
- (unsigned int)namespaceId;
- (unsigned int)namespaceVersion;
- (struct NSString { Class x1; }*)treatmentId;

@end
