/* Generated by RuntimeBrowser.
 */

@protocol TUICandidateViewStyle <NSObject>

@required

- (UIColor *)alternativeTextColor;
- (UIFont *)alternativeTextFont;
- (UIFont *)annotationTextFont;
- (UIColor *)arrowButtonBackgroundColor;
- (double)arrowButtonHeight;
- (NSString *)arrowButtonImageName;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arrowButtonPadding;
- (UIImage *)arrowButtonSeparatorImage;
- (UIColor *)backgroundColor;
- (double)backgroundOpacity;
- (UIFont *)candidateFont;
- (UIColor *)candidateNumberColor;
- (UIFont *)candidateNumberFont;
- (UIColor *)cellBackgroundColor;
- (UIImage *)cellBackgroundImage;
- (UIImage *)cellSeparatorImage;
- (long long)cellTextAlignment;
- (unsigned long long)columnsCount;
- (double)cornerRadius;
- (bool)darkBackdrop;
- (bool)doNotClipToBounds;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })extraCellPadding;
- (bool)fillGridWithLines;
- (double)foregroundOpacity;
- (UIColor *)gridBackgroundColor;
- (struct CGPoint { double x1; double x2; })gridLineOffset;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })gridLinePadding;
- (unsigned long long)gridMaskedCorners;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })gridPadding;
- (UIColor *)groupHeaderBackgroundColor;
- (UIColor *)highlightedAlternativeTextColor;
- (UIColor *)highlightedBackgroundColor;
- (UIColor *)highlightedCandidateNumberColor;
- (UIImage *)highlightedCellBackgroundImage;
- (UIColor *)highlightedRowBackgroundColor;
- (UIColor *)highlightedTextColor;
- (UIImage *)leftEdgeSeparatorImage;
- (UIColor *)lineColor;
- (unsigned long long)maskedCorners;
- (unsigned long long)maxNumberOfProactiveCells;
- (double)minimumCellPadding;
- (double)minimumCellWidth;
- (UIImage *)rightEdgeSeparatorImage;
- (double)rowHeight;
- (bool)scrollDisabled;
- (bool)showsIndex;
- (double)singleSlottedCellMargin;
- (UIImage *)slottedCellSeparatorImage;
- (UIColor *)sortControlBackgroundColor;
- (UIColor *)sortControlColor;
- (UIFont *)sortControlFont;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })sortControlPadding;
- (UIColor *)textColor;

@end
