/* Generated by RuntimeBrowser.
 */

@protocol VideoEncoderInterfaceDelegate <NSObject>

@required

- (void)encoder:(VideoEncoderInterface *)arg1 encodedSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg2 metadata:(AVTimedMetadataGroup *)arg3 presentationTime:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg4 streamId:(NSString *)arg5;
- (void)encoder:(VideoEncoderInterface *)arg1 encodingFailedForStream:(NSString *)arg2;

@end
