/* Generated by RuntimeBrowser.
 */

@protocol VoiceTriggerNotificationInterface

@required

- (void)speakerMuteStateChangedNotification:(bool)arg1;
- (void)speakerStateChangedNotification:(NSDictionary *)arg1;
- (void)voiceTriggerNotification:(NSDictionary *)arg1;

@end
