/* Generated by RuntimeBrowser.
 */

@protocol WBSCompletionListItem <NSObject>

@required

- (unsigned long long)engagementDestination;
- (NSString *)parsecDomainIdentifier;
- (long long)parsecQueryID;
- (SFSearchResult *)sfSearchResultValue;

@optional

- (NSString *)lastSearchQuery;
- (void)setSiriSuggestion:(WBSQuerySuggestion *)arg1;
- (WBSQuerySuggestion *)siriSuggestion;

@end
