/* Generated by RuntimeBrowser.
 */

@protocol WDAppSwooshTableViewCellDelegate <NSObject>

@required

- (void)appsCell:(WDAppSwooshTableViewCell *)arg1 showStorePageWithStoreID:(NSNumber *)arg2;

@end
