/* Generated by RuntimeBrowser.
 */

@protocol WDMedicalRecordCountProviderObserver <NSObject>

@required

- (void)medicalRecordCountProvider:(WDMedicalRecordCountProvider *)arg1 didUpdateCountForCategories:(NSArray *)arg2;
- (void)medicalRecordCountProvider:(WDMedicalRecordCountProvider *)arg1 didUpdateCountForSampleTypes:(NSArray *)arg2;
- (void)medicalRecordCountProvider:(WDMedicalRecordCountProvider *)arg1 didUpdateCountForSampleTypes:(NSArray *)arg2;
- (void)medicalRecordCountProviderDidUpdateAllRecordsCount:(WDMedicalRecordCountProvider *)arg1;

@end
