/* Generated by RuntimeBrowser.
 */

@protocol WFActionDrawerAppsTableViewCellDelegate

@required

- (void)appsTableViewCell:(WFActionDrawerAppsTableViewCell *)arg1 didSelectAppWithBundleIdentifier:(NSString *)arg2;

@end
