/* Generated by RuntimeBrowser.
 */

@protocol WFActionDrawerAppsViewControllerDelegate <NSObject>

@required

- (void)appViewController:(WFActionDrawerAppsViewController *)arg1 didSelectAppWithBundleIdentifier:(NSString *)arg2;

@end
