/* Generated by RuntimeBrowser.
 */

@protocol WFEditWorkflowViewControllerDelegate <WFRunWorkflowViewControllerDelegate>

@optional

- (bool)workflowViewControllerCanRemoveActions:(WFEditWorkflowViewController *)arg1;
- (void)workflowViewControllerDidAddAction:(WFEditWorkflowViewController *)arg1;
- (void)workflowViewControllerDidRemoveAction:(WFEditWorkflowViewController *)arg1;
- (void)workflowViewControllerInvalidatedSuggestions:(WFEditWorkflowViewController *)arg1;
- (void)workflowViewControllerRequestsTutorial:(WFEditWorkflowViewController *)arg1;

@end
