/* Generated by RuntimeBrowser.
 */

@protocol WFEditableLibraryResultsControllerDelegate <WFRunnableLibraryResultsControllerDelegate>

@required

- (void)resultsController:(WFEditableLibraryResultsController *)arg1 handleLegacyMoveFromIndexPath:(NSIndexPath *)arg2 toIndexPath:(NSIndexPath *)arg3;

@end
