/* Generated by RuntimeBrowser.
 */

@protocol WFGallerySubmissionControllerDelegate <NSObject>

@required

- (void)gallerySubmissionDidCancel:(UIViewController<WFGallerySubmissionController> *)arg1;
- (void)gallerySubmissionDidFinish:(UIViewController<WFGallerySubmissionController> *)arg1;

@end
