/* Generated by RuntimeBrowser.
 */

@protocol WFIntentViewControllerDelegate <NSObject>

@required

- (void)intentViewControllerDidConfirmIntent:(UIViewController<WFIntentViewController> *)arg1;
- (void)intentViewControllerDidDismissPlatter:(UIViewController<WFIntentViewController> *)arg1;
- (void)intentViewControllerWasTapped:(UIViewController<WFIntentViewController> *)arg1;

@end
