/* Generated by RuntimeBrowser.
 */

@protocol WFOtherNetworkProviderContext <WFCredentialsProviderContext>

@required

- (bool)WAPIEnabled;
- (NSArray *)WAPIIdentities;
- (NSArray *)WAPIRootCertificates;

@end
