/* Generated by RuntimeBrowser.
 */

@protocol WFParameterState <NSCopying, WFVariableSerialization>

@required

- (NSArray *)containedVariables;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;

@optional

+ (Class)processingValueClass;

- (id)initWithVariable:(WFVariable *)arg1;
- (void)processWithVariableSource:(void *)arg1 parameter:(void *)arg2 environment:(void *)arg3 userInputRequiredHandler:(void *)arg4 valueHandler:(void *)arg5; // needs 5 arg types, found 16: <WFVariableDataSource> *, WFParameter *, long long, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, <WFParameterState> *, void*, id /* block */, void*, void, id /* block */, <NSSecureCoding> *, NSError *, void*
- (void)processWithVariableSource:(void *)arg1 parameter:(void *)arg2 isInputParameter:(void *)arg3 userInputRequiredHandler:(void *)arg4 valueHandler:(void *)arg5; // needs 5 arg types, found 16: <WFVariableDataSource> *, WFParameter *, bool, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, <WFParameterState> *, void*, id /* block */, void*, void, id /* block */, <NSSecureCoding> *, NSError *, void*
- (void)processWithVariableSource:(void *)arg1 parameter:(void *)arg2 userInputRequiredHandler:(void *)arg3 valueHandler:(void *)arg4; // needs 4 arg types, found 15: <WFVariableDataSource> *, WFParameter *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, <WFParameterState> *, void*, id /* block */, void*, void, id /* block */, <NSSecureCoding> *, NSError *, void*

@end
