/* Generated by RuntimeBrowser.
 */

@protocol WFParameterInputViewControllerDelegate <NSObject>

@required

- (void)parameterInputViewControllerDidCancel:(WFParameterInputViewController *)arg1;
- (void)parameterInputViewControllerDidFinish:(WFParameterInputViewController *)arg1 withParameterStates:(NSDictionary *)arg2;

@end
