/* Generated by RuntimeBrowser.
 */

@protocol WFRemoteQuarantinePolicyEvaluatorDelegate <NSObject>

@required

- (<WFUserInterface> *)userInterfaceToPresentAlertForEvaluator:(WFRemoteQuarantinePolicyEvaluator *)arg1;

@end
