/* Generated by RuntimeBrowser.
 */

@protocol WFSettings <NSObject, NSCopying>

@required

- (NSString *)apiVersion;
- (NSString *)apiVersionFallback;
- (NSSet *)aqiEnabledCountryCodes;
- (unsigned long long)locationNumDecimalsOfPrecision;
- (unsigned long long)networkFailedAttemptsLimit;
- (unsigned long long)networkSwitchExpirationTimeInSeconds;

@end
