/* Generated by RuntimeBrowser.
 */

@protocol WFTriggerTextConfigurationViewControllerDelegate <NSObject>

@required

- (void)triggerTextConfigurationViewController:(WFTriggerTextConfigurationViewController *)arg1 didSelectText:(NSString *)arg2;
- (void)triggerTextConfigurationViewControllerDidCancel:(WFTriggerTextConfigurationViewController *)arg1;

@end
