/* Generated by RuntimeBrowser.
 */

@protocol WFWorkflowSettingsViewControllerDelegate <NSObject>

@required

- (void)settingsViewControllerDidFinish:(WFWorkflowSettingsViewController *)arg1;
- (void)settingsViewControllerWantsWorkflowReload:(WFWorkflowSettingsViewController *)arg1;

@end
