/* Generated by RuntimeBrowser.
 */

@protocol WGWidgetIconAnimationExtraViewsProviding <NSObject>

@required

- (NSArray *)extraViews;
- (UIView *)extraViewsContainer;
- (bool)shouldAnimateFirstTwoViewsAsOne;
- (bool)shouldAnimateLastTwoViewsAsOne;

@end
