/* Generated by RuntimeBrowser.
 */

@protocol WKWallpaperLocketViewControllerDelegate <NSObject>

@required

- (void)wallpaperLocketViewControllerDidTapOnDoneButton:(WKWallpaperLocketViewController *)arg1;

@end
