/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftCoreMIDI.dylib
 */

@interface _TtCE8CoreMIDIVSo10MIDIPacket7Builder : Swift._SwiftObject {
    void capacity;
    void packetPointer;
}

@end
