/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPModelStoreBrowseMusicKitRequestOperation : MPStoreModelRequestOperation {
    NSIndexSet * _carPlayWhitelistedFCKinds;
}

- (void).cxx_destruct;
- (id)_produceResponseWithParser:(id)arg1 results:(id)arg2 error:(id*)arg3;
- (id)browseURLWithStoreBagDictionary:(id)arg1;
- (id)configurationForLoadingModelDataWithStoreBagDictionary:(id)arg1 error:(id*)arg2;
- (void)produceResponseWithLoadedOutput:(id)arg1 completion:(id /* block */)arg2;
- (id)radioGenresURLWithStoreBagDictionary:(id)arg1;

@end
