/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
 */

@interface MPMRNowPlayingPlayerPathWrapper : MPCFWrapper

@property (nonatomic, readonly) void*unwrappedValue;

- (id)initWithMRNowPlayingPlayerPath:(void*)arg1;
- (void*)unwrappedValue;

@end
