/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CryptoKit.framework/CryptoKit
 */

@interface _TtCV9CryptoKit24CoreCryptoChaChaPolyImplP33_1EEA2C15408765EA775A4381D63577DE7Context : Swift._SwiftObject {
    void ctx;
}

@end
