/* Generated by RuntimeBrowser
   Image: /usr/lib/swift/libswiftCore.dylib
 */

@interface __SwiftNativeNSArrayBase : NSArray {
    struct RefCounts<swift::RefCountBitsT<swift::RefCountIsInline> > { 
        struct atomic<swift::RefCountBitsT<swift::RefCountIsInline> > { 
            _Atomic struct RefCountBitsT<swift::RefCountIsInline> {} __a_; 
        } refCounts; 
    }  refCounts;
}

+ (bool)automaticallyNotifiesObserversForKey:(id)arg1;

- (bool)_isDeallocating;
- (bool)_tryRetain;
- (bool)allowsWeakReference;
- (id)autorelease;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (oneway void)release;
- (id)retain;
- (unsigned long long)retainCount;
- (bool)retainWeakReference;

@end
