/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface _GCStereoARCustomMotionProfile : GCMotion {
    struct { 
        /* Warning: Unrecognized filer type: '}' using 'void*' */ void*vector; 
    }  _forwardQuaternion;
    bool  _hasSetPrevControllerAttitude;
    struct GCQuaternion { 
        double x; 
        double y; 
        double z; 
        double w; 
    }  _prevControllerAttitude;
}

- (void)_setAttitudeWithControllerUpdate:(struct GCQuaternion { double x1; double x2; double x3; double x4; })arg1;
- (void)_setForwardQuaternion:(struct { })arg1;
- (bool)hasAttitudeAndRotationRate;
- (id)initWithController:(id)arg1;

@end
