/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface GCStereoAR : NSObject {
    struct { 
        /* Warning: Unrecognized filer type: '}' using 'void*' */ void*vector; 
    }  _arcEnd;
    id /* block */  _arcHandler;
    struct { 
        /* Warning: Unrecognized filer type: '}' using 'void*' */ void*vector; 
    }  _arcStart;
    GCController * _controller;
    struct { 
        /* Warning: Unrecognized filer type: '}' using 'void*' */ void*vector; 
    }  _controllerReportedAttitude;
    bool  _measuringArc;
    GCMotion * _motion;
    GCControllerButtonInput * _systemButton;
    GCControllerTouchpad * _touchpad;
    GCControllerButtonInput * _touchpadButton;
    GCControllerButtonInput * _triggerButton;
    id /* block */  _valueChangedHandler;
}

@property (nonatomic, copy) id /* block */ arcHandler;
@property (nonatomic, readonly) GCController *controller;
@property (nonatomic, retain) GCControllerButtonInput *systemButton;
@property (nonatomic, readonly) GCControllerTouchpad *touchpad;
@property (nonatomic, retain) GCControllerButtonInput *touchpadButton;
@property (nonatomic, retain) GCControllerButtonInput *triggerButton;
@property (nonatomic, copy) id /* block */ valueChangedHandler;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_motion;
- (id /* block */)arcHandler;
- (id)controller;
- (struct { })controllerReportedAttitude;
- (void)encodeWithCoder:(id)arg1;
- (void)handleEvent:(struct __IOHIDEvent { }*)arg1;
- (void)handleMotionEvent:(struct __IOHIDEvent { }*)arg1;
- (void)initCommon;
- (id)initWithCoder:(id)arg1;
- (id)initWithController:(id)arg1;
- (bool)isBluetoothAndUSBMirrored;
- (id)productCategory;
- (void)setArcHandler:(id /* block */)arg1;
- (void)setAttitude:(struct { })arg1;
- (void)setAttitudeWithControllerUpdate:(struct { })arg1;
- (void)setController:(id)arg1;
- (void)setControllerAttitude:(struct { })arg1;
- (void)setControllerForElements;
- (void)setDigitizerX:(float)arg1 digitizerY:(float)arg2 timeStamp:(unsigned long long)arg3 touchDown:(bool)arg4;
- (void)setForwardQuaternion:(struct { })arg1;
- (void)setStateFromStereoAR:(id)arg1;
- (void)setSystemButton:(id)arg1;
- (void)setTouchpadButton:(id)arg1;
- (void)setTriggerButton:(id)arg1;
- (void)setValueChangedHandler:(id /* block */)arg1;
- (void)set_motion:(id)arg1;
- (id)systemButton;
- (id)touchpad;
- (id)touchpadButton;
- (id)triggerButton;
- (id /* block */)valueChangedHandler;

@end
