/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Network.framework/Network
 */

@interface NWL2Report : NSObject {
    bool  _cellularKnownGood;
    int  _cellularLQM;
    unsigned char  _cellularPowerCostDownload;
    unsigned char  _cellularPowerCostUpload;
    unsigned char  _cellularRadioTechnology;
    bool  _wifiKnownGood;
    int  _wifiLQM;
    int  _wifiRSSI;
    unsigned char  _wifiRadioTechnology;
}

@property (nonatomic) bool cellularKnownGood;
@property (nonatomic) int cellularLQM;
@property (nonatomic) unsigned char cellularPowerCostDownload;
@property (nonatomic) unsigned char cellularPowerCostUpload;
@property (nonatomic) unsigned char cellularRadioTechnology;
@property (nonatomic) bool wifiKnownGood;
@property (nonatomic) int wifiLQM;
@property (nonatomic) int wifiRSSI;
@property (nonatomic) unsigned char wifiRadioTechnology;

- (bool)cellularKnownGood;
- (int)cellularLQM;
- (unsigned char)cellularPowerCostDownload;
- (unsigned char)cellularPowerCostUpload;
- (unsigned char)cellularRadioTechnology;
- (id)description;
- (void)setCellularKnownGood:(bool)arg1;
- (void)setCellularLQM:(int)arg1;
- (void)setCellularPowerCostDownload:(unsigned char)arg1;
- (void)setCellularPowerCostUpload:(unsigned char)arg1;
- (void)setCellularRadioTechnology:(unsigned char)arg1;
- (void)setWifiKnownGood:(bool)arg1;
- (void)setWifiLQM:(int)arg1;
- (void)setWifiRSSI:(int)arg1;
- (void)setWifiRadioTechnology:(unsigned char)arg1;
- (bool)wifiKnownGood;
- (int)wifiLQM;
- (int)wifiRSSI;
- (unsigned char)wifiRadioTechnology;

@end
