/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface _SFEditablePasswordTableViewController : _SFPasswordTableViewController <SFAddPasswordViewControllerDelegate> {
    UIBarButtonItem * _addBarButtonItem;
    WBSAutoFillQuirksManager * _autoFillQuirksManager;
    UIBarButtonItem * _cancelBarButtonItem;
    UIBarButtonItem * _deleteBarButtonItem;
    UIBarButtonItem * _editBarButtonItem;
    NSMutableArray * _savedPasswordsBySection;
    NSArray * _savedPasswordsMatchingSearchPattern;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addBarButtonItemTapped:(id)arg1;
- (void)_cancelBarButtonItemTapped:(id)arg1;
- (void)_deleteBarButtonItemTapped:(id)arg1;
- (id)_deletePasswordActionTitle;
- (void)_deletePasswordsAtIndexPaths:(id)arg1;
- (void)_editBarButtonItemTapped:(id)arg1;
- (id)_passwordForIndexPath:(id)arg1;
- (void)_reloadPasswords;
- (bool)_shouldShowSectionHeaders;
- (void)_updateDeleteButton;
- (void)_updateMatchingPasswords;
- (void)addPasswordViewControllerDidFinish:(id)arg1 withSavedPassword:(id)arg2;
- (id)initWithSiteMetadataManager:(id)arg1 autoFillQuirksManager:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)searchPatternDidUpdate;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (void)setEditing:(bool)arg1 animated:(bool)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;

@end
