/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface _SFLinkWithPreviewActivityItemProvider : _SFActivityItemProvider

- (id)activityViewControllerLinkPresentationMetadata:(id)arg1;

@end
