/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/SafariServices.framework/SafariServices
 */

@interface _SFUserMediaPermissionController : WBSUserMediaPermissionController

- (void)coalescedAsynchronousWriter:(id)arg1 didFinishWritingData:(id)arg2;
- (void)requestUserMediaAuthorizationForDevices:(unsigned long long)arg1 url:(id)arg2 mainFrameURL:(id)arg3 decisionHandler:(id /* block */)arg4 dialogPresenter:(id)arg5;
- (void)savePendingChanges;

@end
