/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/IOSurface.framework/IOSurface
 */

@interface IOSurfaceRemoteRemoteClient : NSObject {
    id /* block */  _disconnectedHandler;
    NSObject<OS_dispatch_queue> * _disconnectedQueue;
    NSMapTable * _ioSurfaceClients;
    int  _pid;
    NSObject<OS_xpc_object> * _remoteConnection;
}

@property (nonatomic, copy) id /* block */ disconnectedHandler;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *disconnectedQueue;
@property (nonatomic, retain) NSMapTable *ioSurfaceClients;
@property (nonatomic) int pid;
@property (nonatomic, retain) NSObject<OS_xpc_object> *remoteConnection;

- (void).cxx_destruct;
- (void)_addClient:(struct __IOSurfaceClient { }*)arg1 extraData:(id)arg2;
- (struct __IOSurfaceClient { }*)_getClient:(unsigned int)arg1 inboundExtradata:(id)arg2 outboundExtraData:(id*)arg3;
- (void)_handleError:(id)arg1;
- (void)_handleMessage:(id)arg1;
- (bool)_removeClient:(unsigned int)arg1;
- (void)dealloc;
- (id)description;
- (id /* block */)disconnectedHandler;
- (id)disconnectedQueue;
- (id)initWithRemoteConnection:(id)arg1 disconnectedQueue:(id)arg2 disconnectedHandler:(id /* block */)arg3;
- (id)ioSurfaceClients;
- (int)pid;
- (id)remoteConnection;
- (void)setDisconnectedHandler:(id /* block */)arg1;
- (void)setDisconnectedQueue:(id)arg1;
- (void)setIoSurfaceClients:(id)arg1;
- (void)setPid:(int)arg1;
- (void)setRemoteConnection:(id)arg1;

@end
