/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Security.framework/Security
 */

@interface OTConfigurationContext : NSObject {
    NSString * _altDSID;
    SFSignInAnalytics * _analytics;
    NSString * _context;
    NSString * _dsid;
    OTControl * _otControl;
    id  _sbd;
}

@property (nonatomic, copy) NSString *altDSID;
@property (nonatomic, retain) SFSignInAnalytics *analytics;
@property (nonatomic, copy) NSString *context;
@property (nonatomic, copy) NSString *dsid;
@property (retain) OTControl *otControl;
@property (retain) id sbd;

- (void).cxx_destruct;
- (id)altDSID;
- (id)analytics;
- (id)context;
- (id)dsid;
- (id)makeOTControl:(id*)arg1;
- (id)otControl;
- (id)sbd;
- (void)setAltDSID:(id)arg1;
- (void)setAnalytics:(id)arg1;
- (void)setContext:(id)arg1;
- (void)setDsid:(id)arg1;
- (void)setOtControl:(id)arg1;
- (void)setSbd:(id)arg1;

@end
